### ISSUE TITLE
Thermostat temperature changing error z-way 2.0.1-rc28

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#100]
When I change temperature I see error message 
![2015-05-21 15 15 10](https://cloud.githubusercontent.com/assets/2894860/7748378/9243273c-ffcc-11e4-8019-16061988878f.png)

**Comment by PoltoS** [comment]
@vades Note that 1 is HEAT, so it is a UI bug that it sends wrong value

**Comment by vades** [comment]
I can not catch this error. What is the correct value?
