### ISSUE TITLE
Interview Results window don't show real status interview

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#101]
I open Interview Results, and I see that the interview not completed, though under this window are all pluses. Only after page reload Interview Results window show that interview completed.
![2015-05-25 18 28 09](https://cloud.githubusercontent.com/assets/2894860/7799250/68dc6712-030c-11e5-971b-5c7fccf7997c.png)

**Comment by vades** [comment]
Fixed. Please test it on DEV branch

**Comment by vades** [comment]
In the last version (2.0.1) is proccess shown after including
