### ISSUE TITLE
The interview process isn't showed after including

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#102]
I include device, and immediately go to the tab Configuration-->Interview.
I can't see interview process, after page reload all OK.
![2015-05-25 18 41 38](https://cloud.githubusercontent.com/assets/2894860/7799436/bac7411c-030e-11e5-9a74-fa8d52750461.png)

**Comment by vades** [comment]
Same Issue as https://github.com/Z-Wave-Me/ExpertUI/issues/101
Should be fixed on DEV branch
