### ISSUE TITLE
Copy button "Select Device Description" to Configuration tab if No configuration file

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#103]
After including new device I'm going to Configuration tab. If device hasn't description file I see message: **No configuration file**. It is logical that somewhere nearby should be a button "Select Device Description", but it isn't.
![2015-05-25 19 07 02](https://cloud.githubusercontent.com/assets/2894860/7799664/805124e6-0311-11e5-8f94-435bbbf7d01a.png)

**Comment by vades** [comment]
Configuration has a select with device description
![configuration-select](https://cloud.githubusercontent.com/assets/1451741/16232275/281797f8-37ca-11e6-8838-e3483dee3156.png)
