### ISSUE TITLE
Show the set value digit for parameter 

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#105]
In manuals for z-wave devices the parameter value is specified by digits. Propose to add in the parameter description set value for more convenient comparison manual and zddx description

Fibaro Wall Plug manual:
![2015-05-26 16 36 13](https://cloud.githubusercontent.com/assets/2894860/7813652/6a67b910-03c5-11e5-970a-06fbb9ec878e.png)

Show set value in description
![2015-05-26 15 28 16](https://cloud.githubusercontent.com/assets/2894860/7813792/8a8652fa-03c6-11e5-9fe7-10d9d81b8f32.png)

**Comment by PoltoS** [comment]
Это проще и быстрее самому добавить

**Comment by aivs** [comment]
Тогда добавлю и описание разверну, а то никто не догадывается о его существовании

**Comment by aivs** [comment]
Done
