### ISSUE TITLE
Highlight the the selected menu item

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#106]
What about to add highlighting to the selected menu item. This will help to quickly navigate in UI.

![2015-05-26 16 59 43](https://cloud.githubusercontent.com/assets/2894860/7814359/662801f2-03ca-11e5-9e18-f85718928ca0.png)

**Comment by vades** [comment]
Done
![active_1](https://cloud.githubusercontent.com/assets/1451741/8794595/5577cdb0-2f85-11e5-9923-201f9c6f6d85.png)
![active_2](https://cloud.githubusercontent.com/assets/1451741/8794604/5cb668e8-2f85-11e5-87f2-c6a150e9aadd.png)
