### ISSUE TITLE
Sensors label "Idle" or "Trigger" has &nbsp; symbol at end only if the sensors didn't change the status

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#107]
If you open the tab "Sensors" you can see the labels "Idle &nbsp;", and if the sensor is triggered, you can see "Triggered" and then "Idle" WITHOUT &nbsp; symbol.  
And please! make "Triggered" label yellow or red!
![2015-06-03 23 19 57](https://cloud.githubusercontent.com/assets/2894860/7970962/35627c06-0a4a-11e5-9310-cf8083145bbb.png)

**Comment by vades** [comment]
Done
![issue-107](https://cloud.githubusercontent.com/assets/1451741/7979902/93c36e6e-0aa3-11e5-8e10-ca296beebe0e.png)
