### ISSUE TITLE
If unset USER CODE and if not specified user code, then command not sending

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#108]
If I unset user code and not specified user code I see error message:  
![2015-06-05 18 34 42](https://cloud.githubusercontent.com/assets/2894860/8009463/97d7b2a8-0bb1-11e5-9416-d73902ca7778.png)

It's right for this COMMAND CLASS because it needed 3 parameters. But in the right way user should not specify USER CODE when unset USER CODE.

I suggest, if the user choose UNSET, then USER CODE set automatically 1111 in the command. 
In this case, there will be no error  and the user will get what they wanted

**Comment by PoltoS** [comment]
The correct way is to send 12, "", 0.

Seems that current implementation treat empty field as no parameter instead of as empty parameter.

**Comment by vades** [comment]
Now is possible to send empty string with '':
/ZWaveAPI/Run/devices[42].instances[0].commandClasses[112].Set('','',0)
