### ISSUE TITLE
Error handling data from server

### ISSUE THREAD

**Issue by GUNAGANTIGANESH** [Z-Wave-Me/ExpertUI#109]
Hello everyone,
     I downloaded z-way for my Razberry and I am able to control the z-wave switches like on/off , inclusion and exclusion manually and even with a python code . But suddenly now I am getting an error " error handling data from server " whenever i open expert UI interface and unable to control the plugs. Unable to know where is the actual problem. My Razberry receiver(daughter card) is working fine it is not damaged and no problem with it. Would you please help me.
waiting for suggestions to resolve my issue
Thank you.

**Comment by aivs** [comment]
In smarthome UI in Z-Wave module set ttyAMA0

**Comment by GUNAGANTIGANESH** [comment]
I am new to z-wave razberry pi . Would you  please elaborate on how to set ttyAMA0 , i have four interfaces Expert UI, Z-Way Home Automation UI, TV UI, old Expert UI, mobile UI , from there can you please explain the steps.
Thank you

can you also tell me how to uninstall z-way on razberry-pi or how to remove all the packages installed , because i want to reinstall after uninstalling it.
Thank you

**Comment by christianpaetz** [comment]
you can check the Z_Wave port in Smart Home UI ( turn on system apps in "my Settings" under Applications. You can just delete /opt/z-way/server or flash a new sd card for fresh restart
