### ISSUE TITLE
v2.0.1: Configuration does not save device descriptions

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#113]
On a clean rc44 installation, I noticed that under configuration, Device Descriptions are no longer saved. I have a Duwi Wall plug, and a Zwave.me Wall CS inserted. The system had selected the Duwi device descriptor, but nothing for the Wall CS. It even did not detect its device type.
I noticed that I could not add the Device descriptor. Then I tried to just save the Duwi decriptor. That failed!

**Comment by pz1** [comment]
Same behaviour in the final 2.0.1 release. Initially some of the device descriptors were automatically recognised including the images. After one night some descriptors were lost. I have observed that more often in the past years.
In the first place, I don't understand why a device should ever be allowed to loose its device descriptor once it has been explicitly assigned by a user.

**Comment by pz1** [comment]
After a re-include, the Duwi wall plug automatically assigned the Device Description.
I haven't managed to re-include the Zwave>Me Wall CS. This is a very awkward device to control, where I first have to hold four buttons followed by pushing a second button to get it in management mode. This is a bit of guess work since neither the device nor the documentation indicates which button has which number.

**Comment by PoltoS** [comment]
WallC-S manual is here. Buttons are shown: http://manuals.zwaveeurope.com/make.php?lang=en&type=&sku=ZME_WALLC-S

**Comment by pz1** [comment]
This manual indeed shows a different button numbering than I had assumed. Still I can not re-include the device (5 seconds all 4 buttons follwed by a short push on button 1). Wall CS is located within 1 meter of the controller

**Comment by PoltoS** [comment]
Exclude first?

**Comment by pz1** [comment]
Yes, that worked, but the downside is that I in such a situation a new device number is assigined.
Besides it does not bring back the Device Description, and hence the configuration file

**Comment by PoltoS** [comment]
You should see in log ZDDXmlFile DH changed when you select your ZDDX. Do you?

**Comment by pz1** [comment]
This is what the log said:
[2015-07-01 08:37:50.623] [I] [zway] Removing job: Wakeup Sleep
[2015-07-01 08:37:59.140] [I] [zway] Loading ZDDX index from ZDDX/ZDDX.indxml
[2015-07-01 08:38:10.238] [D] [zway] SETDATA devices.8.data.ZDDXMLFile = "undefined"
[2015-07-01 08:38:10.238] [I] [zway] Saving configuration data to config/zddx/ff1b412b-DevicesData.xml
[2015-07-01 08:38:10.575] [I] [zway] Loading ZDDX data from ZDDX/undefined
[2015-07-01 08:38:10.760] [D] [zway] Job 0x13: deleted from queue

**Comment by PoltoS** [comment]
devices.8.data.ZDDXMLFile = "undefined"

Opps... Looks like UI bug, since undefined is sent to backend.
@vades, please take care of this

**Comment by pz1** [comment]
Thanks for this releief. I feared it were clumsy hands ;)
