### ISSUE TITLE
v2.0.1: Can not set device name/location with expert tools

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#114]
Cannot set device name/location with configuration/expert tools
Error handling data
/ZWaveAPI/Run/devices[4].instances[0].commandClasses[119].SetName(node 4)

**Comment by PoltoS** [comment]
Please add " around the text

**Comment by pz1** [comment]
That works. IIRC it worked without quotes in the old blue UI, which is a more natural way of doing it. Also more in line with other text fields in Z-Way

**Comment by PoltoS** [comment]
Fix Expert Commands string fields to add quotes (") around text before assembling command

**Comment by vades** [comment]
The Expert UI/Rename device sends this CMD:
/ZWaveAPI/Run/devices[2].data.givenName.value='Routing Multilevel Switch_2 ren'

From where is this CMD? /ZWaveAPI/Run/devices[4].instances[0].commandClasses[119].SetName(node 4)

From Blue UI?

**Comment by pz1** [comment]
In the old blue UI there was no problem. I do get this in the new Expert UI under Configuration/Expert Commands. (For example with the Zwave>Me wall switches, and StellaZ)
If I do surround the name with quotes as PoltoS sugessted, it does work

**Comment by vades** [comment]
OK. I see the problem

**Comment by vades** [comment]
FIXED - now is string send with quotes;
/ZWaveAPI/Run/devices[42].instances[0].commandClasses[119].SetName('My%20new%20name')
