### ISSUE TITLE
Thermostats seems not to work in Expert UI

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#115]
Please test it.

At least with CT100

http://forum.z-wave.me/viewtopic.php?f=3422&t=21766&p=57103#p57103

**Comment by vades** [comment]
This task is for the SmartHome UI?

**Comment by PoltoS** [comment]
No, this is for expert:
> deeproot wrote:
> In expertui everything seems to work fine except the thermostats are stuck in heat mode and I can not > change them to cool but I can send off, desired temp.

**Comment by vades** [comment]
This should be fixed with: https://github.com/Z-Wave-Me/ExpertUI/commit/1d41ff6e2412d50fe317f7c0b4773a3fa3da729b
