### ISSUE TITLE
Need to refresh the page to see the devices in the list "Replace failed node"

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#116]
I have dead battery device, in list "Mark battery device is failed" I select this device.
After some times in list "Mark battery device is failed" I don't see my device, that I want to remove. But, if I refresh the page, the device appears in the list!  
<img width="571" alt="2015-07-09 14 53 42" src="https://cloud.githubusercontent.com/assets/2894860/8594549/658dcb30-264a-11e5-939e-3f4a77eff35e.png">

**Comment by vades** [comment]
I refactored a little bit section Network/Control

**Comment by ronie-z-wave** [comment]
fixed with https://github.com/Z-Wave-Me/ExpertUI/commit/b664455bd1ee8665c93ed63ff4f7d48b470ca8e9
