### ISSUE TITLE
Duplicated devices in button "+" in Associations

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#117]
How to reproduce duplicates in "+" in Associations:
1)  Press "+" button, no need to press "Add"
2) In list "Configuration for" select this device again
3) Press "+" button, you should see the duplicates

<img width="1134" alt="2015-07-09 18 12 00" src="https://cloud.githubusercontent.com/assets/2894860/8599004/a1fec4a4-2666-11e5-877e-1d41881f769a.png"> 
<img width="1138" alt="2015-07-09 18 12 11" src="https://cloud.githubusercontent.com/assets/2894860/8599009/a7487efa-2666-11e5-9cb2-51a79728c885.png">

**Comment by vades** [comment]
Fixed
