### ISSUE TITLE
Updates not showing in Control view

### ISSUE THREAD

**Issue by chrisSimplyHome** [Z-Wave-Me/ExpertUI#118]
I have an Aeotech Home Energy Meter G2 that works perfectly upon first including the device into the network, but after changing anything in the command class, the Control>Sensors view doesn't show changes on the device unless I poll it. Additionally, if I use the API to see all the recent changes in the network, nothing shows up there (only after I've fiddled with the configuration). I've already spoken with the manufacturer and they've assured me it's something on your end. 

I also have an Ecolink DW-ZWAVE2 door sensor that will behaves oddly in the Control>Sensors view. When the sensor is changing from "Triggered" to not being triggered, the view will update properly, but when going the other way (from not being triggered to "Triggered") no updates are made in the view. Even hitting the "Update" button by the sensor or the "Update All" button has no effect, but refreshing the page does.

**Comment by PoltoS** [comment]
Part 2: indeed, this is a problem and it should be fixed soon (may be even in 2.0.2-rc1 it is)

Part 1: not clear at all.
What means "after changing anything in the command class"? May be your device does not send unsolicited reports? Have you set up Lifeline or reports group? Are you sure these packets reaches Z-Way? Log can help to analyse.

What means "only after I've fiddled with the configuration"?

**Comment by chrisSimplyHome** [comment]
So, in the configuration command class, after I make any changes (regardless of whether or not those changes are supposed to affect how/when/if unsolicited reports are sent), unsolicited reports are no longer received. "Only after I've fiddled with the configuration" means the same thing; that everything works fine after inclusion into the network but before any configuration changes have been made whatsoever. Once any configuration change is made, unsolicited reports are no longer received (even if those configuration changes are not supposed to affect unsolicited reports). 

I know this sounds like an issue on the hardware (which is why I went to that vendor first) but they've assured me that it is not an issue with either their hardware or firmware.

**Comment by PoltoS** [comment]
We need logs before change and after

**Comment by chrisSimplyHome** [comment]
Sure, that's probably the best way! Where can I find the logs you need?

**Comment by chrisSimplyHome** [comment]
Well, I have the log file, but am unable to attach it here, it seems. What's the best way to get it to you?

**Comment by chrisSimplyHome** [comment]
I'd rather not paste the contents of this rather large log file into this text box here, so is there a better way to get the log information to you?
