### ISSUE TITLE
In Configuration tab, Configuration for device_###, Expert commands, CommandClass button doesn't return value without page refresh

### ISSUE THREAD

**Issue by 379820** [Z-Wave-Me/ExpertUI#12]
In Configuration tab select Configuration for some device_### than navigate to Expert commands and click "Get". After clicking corresponding CommandClass button like "SensorMultiLevel" new commandClass window will show up. And there are for example, 
“/: None (17:02)
    3: None (17:20)
        sensorTypeString: Luminiscence (17:02)
        val: 5 (17:20)
        deviceScale: 1 (17:20)
        scale: 1 (17:20)
        scaleString: Lux (17:20)
    supported: true (17:02)
    version: 5 (17:02)
    security: false (17:02)
    interviewDone: true (17:02)
    interviewCounter: 9 (17:02)
    typemask: 4 (17:02)”
 This window doesn’t reflect changes. If the value changes on device and we press "Get" button again it will not show new value (val:263) in commandClass. Only refreshing page will update it with a right one.

**Comment by vades** [comment]
After clicking CommandClass button window reflect changes.
-- Test it --
