### ISSUE TITLE
After the interview completed need to refresh the page to see information about the device

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#120]
It's seen that interview goes, a plus sign appear, but after the interview completed information about the device is not automatically updated.  

After the interview completed, before the page refresh:
<img width="1015" alt="2015-07-10 16 26 18" src="https://cloud.githubusercontent.com/assets/2894860/8619666/7eb92df2-2721-11e5-8fbd-e7fcf8a8a47d.png">

After the page refresh:
<img width="971" alt="2015-07-10 16 27 25" src="https://cloud.githubusercontent.com/assets/2894860/8619671/942bd702-2721-11e5-859a-b593d26d38d5.png">

**Comment by vades** [comment]
This is will be fixed in the new release.

**Comment by pz1** [comment]
Why closing this issue while it has not been resolved? In other places the tag **enhancement** was used. I did interprete that as something not being fixed in this version. It would be a pity if such useful user feedback disappears in a black hole..

**Comment by PoltoS** [comment]
This usually means fixed in internal versions, but you will available for public in next release

**Comment by pz1** [comment]
fine
