### ISSUE TITLE
The applied value is not shown in settings

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#121]
When apply settings, underline should be below actual value, but it's not.

On screenshot actual value is On (value 255, in expert commands it is), but underline under Off.
Page refresh don't support.
<img width="456" alt="2015-07-15 18 27 57" src="https://cloud.githubusercontent.com/assets/2894860/8702422/564f5ee2-2b20-11e5-87bc-35d83cef99b5.png">

**Comment by pz1** [comment]
Just my 2 cts: This problem did exist already in 1.5 or earlier. I could fix that by saving by clicking "on" (in this case) followed by a save. Sometimes I needed to select the only underlined option, Save and check the desired setting again.
But is is strange behaviour indeed.

**Comment by vades** [comment]
Underline is below the "Default value".

**Comment by vades** [comment]
Sorry, underlined should be "Actual value"

**Comment by pz1** [comment]
This confuses me. On a AwaveMe wall switch I just chaged setting from " Operated by Indicator Command Class" to "Show switch state" The underline stays at the original setting, even if the interface says that it was updated. Also a retrieve from device does not make it change. So to me it seems under lined is NOT the actual value

**Comment by vades** [comment]
The underline stays at the original setting......  Do you mean "Default settings"
What is better?
1. To underline the "Actual value"? Why should be actual value "underlined" if is also "checked"?
2. To underline the "Default value"?
Now is underlined the "Default value"

**Comment by PoltoS** [comment]
guys, underlined should be last known from Z-Wave protocol, checked last saved user selection (not always actual for battery devices). Default can also be marked somehow. In old Blue it was written as text. We can make small "link" with "set to default"

**Comment by pz1** [comment]
>  *Default can also be marked somehow. In old Blue it was written as text.*

Just checked.
... 
    updated: 29.06.2015 | Set value: 3 | Default value is: 3 - Operated by Indicator Command Class
...
So the relevant info is there. Don't see the added value of underlining

**Comment by vades** [comment]
1. Checked: Last saved user selection
2. Underlined: Default  - last known from Z-Wave protocol
3. Alert text: if user selection is not stored in device - stored in config only.
4. Link added - set value to default.

![issue-121](https://cloud.githubusercontent.com/assets/1451741/8925321/32aea7e0-3507-11e5-8f84-1734a5cb709a.png)

**Comment by pz1** [comment]
The named link to default value is more user friendly indeed. Do I understand correctly that after the value has been stored in device, the underlining goes to ALARM SMOKE frame?
If not, please explain what you mean by
>  last known from Z-Wave protocol

**Comment by vades** [comment]
1. The named link to default value is more user friendly indeed - true
2. Default (underlined) comes from zddx xml:
<configParam number="1" type="range" size="2" default="0000">

![issue-121](https://cloud.githubusercontent.com/assets/1451741/8931392/4473bda6-3536-11e5-8100-e15640f56d0f.png)

**Comment by pz1** [comment]
Ah, factory setting. Thanks

**Comment by aivs** [comment]
Are we came to the conclusion that the underlined is the current value?

**Comment by pz1** [comment]
> Are we came to the conclusion that the underlined is the current value?

From this thread the terms *Set value, Current value*, and *Default value* are still confusing to me. I don't even know if each of them represents a different notion.

**Comment by PoltoS** [comment]
@vades last know does not mean Default.

Last known is the value obtained from Configuration.data[xxx].val

Current selected by user is the one from Configuration.xml saved by the ui - for battery device this might be not the current util nect wakeup. In this case we need to write a warning like you did that the value was not yet accepted by the device.

Default should be taken from ZDDX and should be in description with a link Restore to default - it will change the selection to the default value.

Please change it
