### ISSUE TITLE
show values of Vibaro Motionsensor 

### ISSUE THREAD

**Issue by schleicheisen** [Z-Wave-Me/ExpertUI#122]
some values are shown false in the input field, but it seems that they are stored correct

affected values are:
- Nº 42 - ILLUMINATION REPORTS INTERVAL
- Nº 16 - BASIC OFF command frame value
- Nº 64 - TEMPERATURE REPORTS INTERVAL
- Nº 66 - TEMPERATURE OFFSET

the Software Version is 2.01

![fibario-motion-sensor](https://cloud.githubusercontent.com/assets/13415088/8772858/cd698dba-2ecf-11e5-94f4-86fd408d96ed.jpg)

**Comment by vades** [comment]
Can you please clarify, when this error ocurs? I tested Fibaro Sensor and can not reproduce this error.
![122](https://cloud.githubusercontent.com/assets/1451741/10610443/15daa73a-7748-11e5-92ab-911ea7af46de.png)

**Comment by zwave-mke** [comment]
Hi, thats a problem of device description file.
