### ISSUE TITLE
There is no way to stop the process of replacing a failed node

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#123]
Need a stop inclusion button in "replacing a failed node" mode

<img width="1280" alt="2015-07-20 16 32 51" src="https://cloud.githubusercontent.com/assets/2894860/8776903/159aa7ae-2efd-11e5-903b-221265725b91.png">
<img width="1280" alt="2015-07-20 16 33 01" src="https://cloud.githubusercontent.com/assets/2894860/8776904/16b057ba-2efd-11e5-9dd5-5b9f449aa1cd.png">

**Comment by vades** [comment]
Now are buttons "Stop Inclusion integrated" after "Replace failed node" 
1. Replace failed node cmd: /ZWaveAPI/Run/ReplaceFailedNode(3)
2. Stop Inclusion cmd: /ZWaveAPI/Run/controller.AddNodeToNetwork(0): server response is: 500 Error Invalid operation 
Seems that "Stop Inclusion" after replace node causes an Error

![issue-123](https://cloud.githubusercontent.com/assets/1451741/8907389/db4d1612-3475-11e5-8a0a-136f3c6beb01.png)

**Comment by PoltoS** [comment]
Checked specs, unfortunately Z-Wave SDK does no allow to stop ReplaceFailedNode call at all.

So, forget about the issue. May be write this in the text.

@aivs please make EN and RU text. @vades can make DE text after this. And we close the issue

**Comment by vades** [comment]
EN and DE text is updated. Please update RU:
"nm_controller_state_19": "Replace Failed Node ready to include replacement device. This action does not allow to cancel the inclusion process",
 "nm_controller_state_19": "Controller ist bereit zum Inkludieren eines neuen Gerätes. Diese Aktion erlaubt es nicht, die Inklusion abzubrechen",

![issue-123](https://cloud.githubusercontent.com/assets/1451741/8924964/edc80296-3503-11e5-9569-41e065060a87.png)

**Comment by aivs** [comment]
Mat be show countdown timer?
