### ISSUE TITLE
In Associations allow to set MCA to node:0 (instance 0).

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#129]
Old case with just node (no channel) should be called in another way ("plain association").

This is new in Z-Wave, so we need to adopt it

**Comment by vades** [comment]
Please more detailed explanation of "plain association" and how to adopt it

**Comment by PoltoS** [comment]
Now we should allow:
"Plain association": just add to Association group (as before, but instead of 0 write "Plain association" or similar (ask CP or MK))
"Channel association": add to MCA group with channel number (as before, but now the number should start from 0 and not from 1).

So, we rename 0 to "Plain" and add one more option 0 to MCA.

**Comment by ronie-z-wave** [comment]
@aivs:  Please test it.

**Comment by aivs** [comment]
Plain association works fine
