### ISSUE TITLE
In Configuration Settings for range field not shown description label

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#134]
If parameter has more than two value, description label shown for all values.
If parameter has only one range field, description label not shown, but in zddx file it's present.
<img width="1280" alt="rangedescription" src="https://cloud.githubusercontent.com/assets/2894860/9380434/c500a9f2-4738-11e5-9027-b9189382cae3.png">

**Comment by vades** [comment]
I can not reproduce this behavior.

**Comment by vades** [comment]
I see the error

**Comment by vades** [comment]
Fixed
![134](https://cloud.githubusercontent.com/assets/1451741/10630529/6e5713fa-77d7-11e5-9d6b-1ef7fc84bd6e.png)
