### ISSUE TITLE
No need to hide information from users. Configuration Settings --> Parameter description

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#135]
Bad idea to hide parameter description in the "info button".
Description do not take up much space. Please show it on next line!!! 
This button only complicates the learning process.

<img width="1026" alt="2015-08-20 12 49 45" src="https://cloud.githubusercontent.com/assets/2894860/9380643/3b7d165a-473a-11e5-970d-1b33ff0ed620.png">

**Comment by vades** [comment]
Parameter descriptions are not 
![135](https://cloud.githubusercontent.com/assets/1451741/10604127/9b003806-7722-11e5-9832-9d31557d56e4.png)
hidden
