### ISSUE TITLE
Revert back freq separation by chip types

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#137]
Please revert back your changes to have frequencies grouped by chip types:

EU/RU/MY/IN/CN
US/ANZ/BR/HK/IL
JP/KR/TW

(please confirm the regroupping with @christianpaetz ).

I would even write that depending on filter installed on the UZB/RaZberry frequencies not from the group of native will work in a range of 1 meter.

**Comment by PoltoS** [comment]
Also the lable about unknown/support/.... should be near "Current freq", not on the top

**Comment by vades** [comment]
Reverted
![137](https://cloud.githubusercontent.com/assets/1451741/10509251/0a04b182-732c-11e5-8eb3-161aa9dcb46a.png)
