### ISSUE TITLE
Need to show value number for parameter

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#140]
For more convenient settings, you need to know the number of the parameter value.
<img width="1280" alt="2015-08-21 17 42 51" src="https://cloud.githubusercontent.com/assets/2894860/9411231/74e77b08-482d-11e5-83a2-e83704bbb1e2.png">

**Comment by vades** [comment]
Added number of params
![140](https://cloud.githubusercontent.com/assets/1451741/10511287/70e3828c-7338-11e5-8bd9-6e351b70584c.png)
