### ISSUE TITLE
Restoring backup impossible +  "Error handling data from server"

### ISSUE THREAD

**Issue by NicolasRT** [Z-Wave-Me/ExpertUI#144]
Managing my automation properties has lead to a lost of some functionalities (trap events from remotes). Hopefully, I made a backup few hours before in the expert UI. Unfortunatly, the UI returns that restoring backup has failed. Then the "Error handling data from server" has became the only answer I could get. I've tried to set again the ttyAMA0 but nothing is changing . If I reinstall Z-way, the UI is now able to include/exclude devices, but all my config is lost. If I try again to restore the backup file I'm obtaining again the "Error handling data from server".
I'm working with raspberry + razberry and I manage it from the webserver (Chrome on a windows seven platform).

Many thanks in advance for your help.

**Comment by PoltoS** [comment]
We need log. Also try to just take from your backup config/zddx/nnnnnnnn-DevicesData.xml and put it into z-way-server folder.

**Comment by NicolasRT** [comment]
Many thanks for your answer. In fact I've reinstalled all and lost the log file. Next time, if it happens again I will take care of that.
