### ISSUE TITLE
UserCode Set() sends wrong command. ZWay 2.1.1

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#145]
If you press Set, the command is send:
http://192.168.0.170:8083/ZWaveAPI/Run/devices[15].instances[0].commandClasses[99].Set('',12,5558,1)

Should:
http://192.168.0.170:8083/ZWaveAPI/Run/devices[15].instances[0].commandClasses[99].Set(12,5558,1)

<img width="1280" alt="2015-09-22 19 09 37" src="https://cloud.githubusercontent.com/assets/2894860/10024100/38845df8-615e-11e5-9f6f-49b61e36bd85.png">.

**Comment by christianpaetz** [comment]
Tested with Wintop Keypad and works fine. Number are sent as ASCII
