### ISSUE TITLE
Not works Restore z-wave network to new Z-Stick

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#148]
I tried to migrate the z-wave network from the stick 3 generation to the stick 5 generation.

Backup creating fine, but when I tried to restore backup, I saw a message:
"Upload or restore of backup has failed".

I checked the folder config, it was empty.

<img width="1280" alt="2015-09-27 21 49 24" src="https://cloud.githubusercontent.com/assets/2894860/10124683/9d80b07c-6563-11e5-84dc-421d8f2e67de.png">

**Comment by PoltoS** [comment]
log

**Comment by pz1** [comment]
[On the forum](http://forum.z-wave.me/viewtopic.php?f=3424&t=21011) we never got this recipe right either

**Comment by aivs** [comment]
[root@ArchServer z-way-server]# LD_LIBRARY_PATH=./libs ./z-way-server 
Z-Way version v2.1.2-rc2 from 2015-09-14 03:08:06 +0300 (build 5001aad6461815ea3053446de965f443cfb45552)
Looking for modules in ./modules
Module modws.so loaded
Module modzbw.so loaded
Module modinstaller.so loaded
Module modsockets.so loaded
Module modhomekit.so loaded
Module modhttp.so loaded
Module modenocean.so loaded
Module moddhs.so loaded
Module modzwave.so loaded
Module modcrypto.so loaded
Using default configuration file config.xml
Error: 'debug-port' number is out of range. Skipping it.
Segmentation fault (core dumped)

**Comment by PoltoS** [comment]
Ждём обновления от Лёхи. Если не поможет, будем собирать инфу. Держи открытым изуес

**Comment by PoltoS** [comment]
Works now
