### ISSUE TITLE
v2.1.1.  After 20 days of no wake-ups on Danfoss LC, device still not declared dead

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#149]
The last wakeup of my Danfoss Living Connect (older device) was on 25.9.2015. Until today it still is not recognised as dead
![wake](https://cloud.githubusercontent.com/assets/7747627/10513339/405868b2-7347-11e5-8417-7eed1249a43f.JPG)

**Comment by christianpaetz** [comment]
Thats ok. The controller can not detect if a battery device is failed. Therefore we have the function "make battery device as failed".  We dont want to add an automatic "failed" if wakeup time was exceeded. may be the battery was just taken out
