### ISSUE TITLE
Show caps in the UI to understand current license type

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#150]
controller.data.caps.

**Comment by vades** [comment]
Is this integrated in the dataholder? I have only:
controller.data.capabilities": {
"value": [
2,
3,
4,
5,
6,
7,

**Comment by vades** [comment]
Caps might look like this:
![capabilities](https://cloud.githubusercontent.com/assets/1451741/10603033/41aa515c-771c-11e5-805a-d7df371b825c.png)

**Comment by PoltoS** [comment]
You need to output controller.data.caps, not capabilities

This should be in near UID. Please split it into:
Subvendor: (first two bytes, show in hex like 0x0115 or 0115)
Nodes limit: third byte (FF means unlimited)
Capabilities: (forth byte & 0x01 = S (True) or s (false) , forth byte & 0x02 = l (true) or L (False), forth byte & 0x04 = M (true) or m (false)

**Comment by vades** [comment]
Fixed

**Comment by PoltoS** [comment]
bed5148 fixed it for real.
