### ISSUE TITLE
Change SetLearnMode(mode) buttons

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#151]
New allowed value added: 2 for NWI.

So, we need two buttons:
Classical Learn Mode (1 - was true)
NWI Learn Mode (2 - new value)
Both should change (like now) to stop on learn mode active (value 0 - was false).

This is required by Z-Wave cert changed rules.

**Comment by vades** [comment]
But values are already changed:
controller.SetLearnMode(1)
controller.SetLearnMode(0)

**Comment by vades** [comment]
New NWI button added and sends: ZWaveAPI/Run/controller.SetLearnMode(2)
![151](https://cloud.githubusercontent.com/assets/1451741/10603730/f87c443c-771f-11e5-9342-3c0851a91dbf.png)
