### ISSUE TITLE
New feature "Select Dongle"

### ISSUE THREAD

**Issue by vades** [Z-Wave-Me/ExpertUI#153]
I've created new feature on Home site Select Dongle
1.Getting data from /ZWave/list
2.If there is more than one instance a dropdown list with dongles is shown. 
3.By selecting a dongle from the dropdown list is URL /ZWaveAPI/ is changed to   /Zwave.prefixname/
4. Default dongle is "zway" -> /Zwave.zway/
5. Current dongle is saved in app cache and also in cookie.

Pleas test it:
PULL branch "ref-home": https://github.com/Z-Wave-Me/ExpertUI/tree/ref-home
or download: https://github.com/Z-Wave-Me/ExpertUI/archive/ref-home.zip

![dongle-design](https://cloud.githubusercontent.com/assets/1451741/10639336/f35ce4d4-780f-11e5-892f-eecd0d942fb7.png)

**Comment by PoltoS** [comment]
Perfect!

@vades can you ask Marcel or someone else to test it (you cen add two Z-Wave bindings for two ports and different names).

And please invite Marce lere on the git hub, so I can reffer to him too in my messages.

**Comment by PoltoS** [comment]
![zway1](https://cloud.githubusercontent.com/assets/3664383/10715213/184ba4f8-7b1f-11e5-915c-34743cfff794.png)

Looks like the selection affects nothing ;(

**Comment by PoltoS** [comment]
Also empty line is in the drop down list

**Comment by PoltoS** [comment]
And if there is only one dongle in the list, switch to it. Note that it might be not only zway.

To check this please remove first dongle keeping the second (or rename zway to zwayXX in the only existing instance of Z-Wave module and make sure Expert UI uses it)

**Comment by vades** [comment]
Fixed

**Comment by PoltoS** [comment]
Martin, looks like the URL is not applied to Network management. Please make sure to update ALL URLs

This resulted in @aivs resetting wrong donlge (his home network) ;(

**Comment by ronie-z-wave** [comment]
{zwayName: name} needs to be in namespaces added by ImportRemoteHA too

**Comment by PoltoS** [comment]
> {zwayName: name} needs to be in namespaces added by ImportRemoteHA too
No, since ImportRemoteHA have it's own names not overlaping with Z-Wave Binding and they have different concept. You can not work with ImportRemoteHA via Expert UI - this is only on ZAutomation level of work.

**Comment by PoltoS** [comment]
BTW, this looks to work now except for sometimes if I work in two tabs I get mixed zways. Make sure not to save currently selected zway in a browser-wise cookie or localstorage - use only JS variable that is in the scope of a tab! And make sure that new tab inherits this somehow... (how?!). Otherwise working in two tabs is a nightmare and requires two browsers. Users will not get it

**Comment by aivs** [comment]
All Ok
