### ISSUE TITLE
Need to add descriptions about colors of Routing Table

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#154]
I always forget what means each color of cells, descriptions are needed the same as for Timing Info.
<img width="1280" alt="2015-10-22 23 09 15" src="https://cloud.githubusercontent.com/assets/2894860/10677027/ad61c6e4-7912-11e5-82d3-1961aaa48fde.png">
<img width="1280" alt="2015-10-22 23 15 30" src="https://cloud.githubusercontent.com/assets/2894860/10677048/cdf81840-7912-11e5-9758-154adc3456ae.png">

**Comment by vades** [comment]
Added
![routing](https://cloud.githubusercontent.com/assets/1451741/16044163/964d22f6-3243-11e6-9ffe-7dfa56b0ccba.png)

**Comment by aivs** [comment]
More good with detailed comments https://github.com/Z-Wave-Me/ExpertUI/commit/fc7321279ebe51f7ca0d5d045f6c1f7edb787bc0, with top margin and without dots https://github.com/Z-Wave-Me/ExpertUI/commit/143cada8f79a577fdb757b365bbb03ca095fbe8c
<img width="787" alt="2016-06-15 16 01 35" src="https://cloud.githubusercontent.com/assets/2894860/16080640/76eab94e-3312-11e6-8384-38fb1196f495.png">
