### ISSUE TITLE
2 zway together problem. v2.1.2-rc12

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#156]
I have tested how works two zway together. 
I chose ZWAY1 in ExpertUI, and started "Controller Factory Default", after this all devices were removed BUT from ZWAY, not from ZWAY1. Its a fail!
Exclude/Include starts for ZWAY.
So all network functions works with ZWAY, but on Configuration tab I see devices from ZWAY1.

**Comment by vades** [comment]
Fiexed. - please test it

**Comment by aivs** [comment]
rc17, expert ui works only with ZWAY, I cant start exclude/include and other processes fro ZWAY1

**Comment by ronie-z-wave** [comment]
#153

**Comment by PoltoS** [comment]
Works now
