### ISSUE TITLE
Associations management is still broken

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#157]
Trying to delete association (it is not in the device, but in the Config). I get this error
![assoc](https://cloud.githubusercontent.com/assets/3664383/11166129/90d4c3f4-8b38-11e5-91bb-d7d942857c84.png)

Found worng commands in Configuration.xml like:
<deviceconfiguration id="109" instance="0" commandclass="142" command="Set" parameter="[2,1,0]"/> (few like this)

Removed them (all with id="109"). Now I see this:
![assoc3](https://cloud.githubusercontent.com/assets/3664383/11166114/f3fa351e-8b37-11e5-8b2c-68b3464e56c1.png)

Where these values are taken from? If I look into resources loaded, Configuration.xml does not contain any line about id="109"

Also I tried to add new node, but I got this:
![assoc2](https://cloud.githubusercontent.com/assets/3664383/11166133/a1d59dfe-8b38-11e5-9d77-0278393edcb7.png)

Clearly the target device (device I add in this group) does not contain any instace.

This is related to https://github.com/Z-Wave-Me/ExpertUI/issues/129

Please fix it finally! Installers gets angy!

**Comment by vades** [comment]
Updated

**Comment by PoltoS** [comment]
Add new item at the end, not in the beginning on the list

**Comment by ronie-z-wave** [comment]
seems to work
