### ISSUE TITLE
In expert commands SwitchBinary 0 is sent instead of 255

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#164]
See selected radio button and network log

![screenshot from 2015-12-11 19 48 45](https://cloud.githubusercontent.com/assets/3664383/11749681/4267118c-a040-11e5-807a-36ae338d9f52.png)

**Comment by PoltoS** [comment]
And why off is underscored? What does it mean?

**Comment by PoltoS** [comment]
Same with SwitchMultilevel, but 255 instead of 0. How can this happen?

![screenshot from 2015-12-11 19 50 46](https://cloud.githubusercontent.com/assets/3664383/11749744/8b9b94f4-a040-11e5-8e3d-390e98d47819.png)

**Comment by PoltoS** [comment]
Looks to have same root as #184

**Comment by vades** [comment]
This bug was solved with 
https://github.com/Z-Wave-Me/ExpertUI/commit/996ab522f7080fd16c3edce2b79982235aa335d0

**Comment by aivs** [comment]
Switch Multilevel and Switch Binary send right commands.
<img width="1280" alt="2017-03-09 19 15 34" src="https://cloud.githubusercontent.com/assets/2894860/23759084/cb122a7c-04fc-11e7-9e57-46f6032afef6.png">
<img width="1280" alt="2017-03-09 19 14 51" src="https://cloud.githubusercontent.com/assets/2894860/23759089/cf0913c0-04fc-11e7-94fe-7eb2d9fc35e3.png">
