### ISSUE TITLE
Firmware Update (Controller) Version Display Error

### ISSUE THREAD

**Issue by ripper121** [Z-Wave-Me/ExpertUI#165]
![2015-12-14_1108](https://cloud.githubusercontent.com/assets/11836272/11778195/3de571b6-a253-11e5-8463-49abfefebb0b.png)

Is this ok?
There is a Float number for FW Version and also a Hex number. So the User can easily see if the newest is installed.

**Comment by PoltoS** [comment]
This is ok. Bootloader have no version but hex checksum only. But it can be installed knly onba specific version of the fw.

For fw update you will see 5.03->5.04 as expected.

Bootloader needs to be updated only once. But we can not check current bootloader version, so the line persists even after update
