### ISSUE TITLE
Request: Display device location on Interview tab

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#166]
At some point (iirc) the good old "blue interface" did display the _deviceLocation_ in the Interview screen. This is very useful in maintenance for battery driven devices, like my StellaZ RTVs. For some time I made location part of the name, but that proved to be bad practice as proved by a number of system crahes/updates, which wiped device names.
So the addition of location information if available would be very welcome, also for devices other then the battery driven.

**Comment by zwave-mke** [comment]
Hi, for now you can use the device-name field to.
