### ISSUE TITLE
Bug: Associations tab does not work for devices with multiple instances/endpoints

### ISSUE THREAD

**Issue by geirgp** [Z-Wave-Me/ExpertUI#167]
I have a Qubino ZMNHDD1 dimmer which supports group associations on 4 endpoints:
Instance 0: 11 Groups
Instance 1: 4 Groups
Instance 2: 4 Groups
Instance 3: 4 Groups

expert ui fails to support this on several levels:
# ng-repeat with non-unique tracker

The "associations" tab currently causes a js error for this device as the angular code uses device.groupId as unique index in the ng-repeat directive.  

Error message:

```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: v in assocGroups track by v.groupId, Duplicate key: 1 http://errors.angularjs.org/1.2.14/ngRepeat/dupes?p0=v%20in%20assocGroups%20track%20by%20v.groupId&p1=1 at angular.js:78 at ngRepeatAction (angular.js:19625) at Object.$watchCollectionAction [as fn] (angular.js:11828) at Scope.$digest (angular.js:11930) at Scope.$apply (angular.js:12179) at done (angular.js:7939) at completeRequest (angular.js:8142) at XMLHttpRequest.xhr.onreadystatechange (angular.js:8085)
```

This can be fixed by changing `expert/app/views/configuration/assoc.html:29` from:
`<tr ng-repeat="v in assocGroups track by v.groupId">` 
to:
`<tr ng-repeat="v in assocGroups track by $index">`

Or at least partly fixed, the page now loads, with the correct number of association groups (24= 11+4+4+4).

More problems though:
# association groups for endpoints => 1 are displayed incorrectly

Labels for the association groups for endpoints >= 1 are repeated using the same group id as for instance 0: instances 1-3 all have incorrect labels taken from the matching group id in instance 0.

If i set up an association for group 2 on instance 0, it is repeated 3 times in the ui - once for every instance >= 1. 

Also, any button for association groups in instances 1-3 act on instance 0, so they're completely faulty.

These issues probably has to do with the fact that this part of the code does not consider instance and instead bluntly uses `assocGroupsDevices` which only holds information for assoc groups in instance 0.
# zddx file does not support group associations for endpoints >= 1?

This Qubino dimmer did not have a ZDDX file, so I had to create one myself https://github.com/Z-Wave-Me/z-way-issues/issues/90 . I created this file by clicking "ZDDX Code Generator" on the "Interview tab", entered descriptions for the 11 association groups in the generated file, and added all the configuration parameters as per the device documentation.

The zddx file generated by zway included only 11 of the 23 association groups (missing 12 assoc groups for endpoints 1-3). Since the generated `assocGroup` -elements did not reference the instance I assume they default to instance 0, and had no way of adding the ones for instances 1,2 & 3. 

Is there an element one can add to `assocGroup` to specify instance, or does that have to be implemented too?

**Comment by vades** [comment]
Assoc are now tracked by $index
<tr ng-repeat="v in assocGroups track by $index">
