### ISSUE TITLE
Bug: Expert commands use input field from instance 0, regardless of the actual instance

### ISSUE THREAD

**Issue by geirgp** [Z-Wave-Me/ExpertUI#168]
To reproduce this error you need a device that supports the Association CC on 2 or more instances (or probably any device that has the same CC on multiple endpoints and a button that produces error message when corresponding field has incorrect value). 

I found the bug when using "Expert commands" on a Qubino Flush dimmer ZMNHDD1. It has 4 instances and supports "Association" cc on all 4.

zway version: 2.2

How to reproduce:
1. Go to "Expert commands" in expert UI
2. Find the "Association" for instance "0" and locate the input field for "Get" -button
3. Enter a number that is too high (higher than number of supported assoc groups for the device) in that field - for this device any number higher than 11.
4. Scroll down to "Association" for a different instance, e.g. "1", don't change the input field (default "1")
5. Click the "Get" button

Result:
Browser pops up alert: "Error handling data
/ZWave.zway/Run/devices[15].instances[1].commandClasses[133].Get(20)"
<img width="769" alt="screen shot 2016-01-03 at 23 15 06" src="https://cloud.githubusercontent.com/assets/986774/12081096/35f2370a-b270-11e5-8c98-69aa170d3f7d.png">

Conclusion:
"Get" button issued a http request using the correct instance id (1) and command class (133), but the value (20) was taken from the wrong input field (Associations/Get for instance 0) on the page.

**Comment by vades** [comment]
Fixed. The problem was with the same IDs in the forms
