### ISSUE TITLE
In Configuration don't show self

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#169]
In Configuration on selection of self (usually 1, but correctly to check agains controller.data.nodeId.value) don't show own interview, but show some message.

I would even remove self from the list. And if no devices, just show a message that you have no devices included. This "uninterviewed" controller makes people frustrated.

**Comment by vades** [comment]
Configuration is hidden for SELF:
nodeId == 255 || nodeId == controllerNodeId || node.data.isVirtual.value
Please test it
