### ISSUE TITLE
I'm voting for removing combo box on the tob of Config tab to be replaced by a list on the left

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#17]
As it was in the old UI. Current layout is one more mouse movement and one more click.

**Comment by Mirarkitty** [comment]
Yes, please.

(Actually it would be nice with a page with all the sensor readings - especially timestamp - switchability and configuration on one page.)

**Comment by aivs** [comment]
This day has finally come! We have easy list of devices.


<img width="1280" alt="2017-03-09 15 46 03" src="https://cloud.githubusercontent.com/assets/2894860/23750825/bf6d5826-04df-11e7-824c-12323fa8503f.png">
