### ISSUE TITLE
V2.2.1-rc3: Still falure of Update bootloader for 05.02 to 34A9

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#171]
![capture](https://cloud.githubusercontent.com/assets/7747627/12235607/1a6a280c-b875-11e5-99ea-baf28f0a7fb7.PNG)

**Comment by PoltoS** [comment]
You have certainly already updated it. It will disallow to update again. Need log to prove it

**Comment by pz1** [comment]
Yes, I tried it before with 2.2.0, which gave the same error. I am sending the log by mail directly to you.
Anyhow, I think we need a different message here

**Comment by PoltoS** [comment]
Confirmed as UZB1 bug (wirmware bug). New Z-Way version will handle this with care.

Anyway, bootloader was upgraded with success (just report was wrong). 2.2.1-rc4 will fix this

**Comment by PoltoS** [comment]
thanks for logs!

**Comment by PoltoS** [comment]
Fixed.
