### ISSUE TITLE
Error in the UserCode Set() command

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#172]
If you set UserCode started not from digit "0", all ok, but if you need to set UserCode started from "0", as example "0123", you will see error message. ExpertUI send command:  
http://192.168.0.70:8083/ZWave.zway/Run/devices[2].instances[0].commandClasses[99].Set(9,0123,1)
should
http://192.168.0.70:8083/ZWave.zway/Run/devices[2].instances[0].commandClasses[99].Set(9,"0123",1
)
We need use quotes! Please fix it.
<img width="957" alt="2016-01-19 18 37 46" src="https://cloud.githubusercontent.com/assets/2894860/12423662/8c65cbf0-bedd-11e5-9737-7bb25c80c5f6.png">

**Comment by PoltoS** [comment]
Duplicate to #184

**Comment by vades** [comment]
This bug was solved with https://github.com/Z-Wave-Me/ExpertUI/commit/c2d15853e600938b3a800ce7fdc276a2f65ffbdb
