### ISSUE TITLE
In Association tab Association to 118:0 write # 118.0 and not just # 118.

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#173]
Otherwise 118:plain and 118:0 both looks like # 118

**Comment by vades** [comment]
Fixed

**Comment by aivs** [comment]
Plain and 0 separately
<img width="616" alt="2016-06-15 19 51 42" src="https://cloud.githubusercontent.com/assets/2894860/16089172/a2908efa-3332-11e6-9a87-259141e0fe35.png">
