### ISSUE TITLE
Can't configure second parameter

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#174]
On Configuration tab I can configure one parameter, then I want configure second parameter, but when I set radio-button, it jump back. Try it!

![configure_bug](https://cloud.githubusercontent.com/assets/2894860/12915419/224d64a2-cf3c-11e5-8ea5-6545d3d66ef0.gif)

**Comment by PoltoS** [comment]
Looks related to https://github.com/Z-Wave-Me/ExpertUI/issues/184

**Comment by vades** [comment]
"I can't catch this bug on my BOX

**Comment by aivs** [comment]
![expert2](https://cloud.githubusercontent.com/assets/2894860/16078907/06802e8a-330a-11e6-9b5a-bce50c624d6c.gif)
To reproduce bug press button "Save this parameter" or "Set to default", after that try to change any parameter, radio button will jump.
And new BUG, if parameter have field that can be disabled, radio button remains not active after click on it.

**Comment by vades** [comment]
_And new BUG, if parameter have field that can be disabled, radio button remains not active after click on it._
![disabled-radio](https://cloud.githubusercontent.com/assets/1451741/16188305/168ea71a-36d5-11e6-851e-51287a23a21e.png)


This is not a BUG. The radio is disabled because to avoid to send a value from this radio. We need a value from text input. If you click on another radio, this is again enabled

**Comment by aivs** [comment]
Gray color shows that field is disabled!
Why in case on picture radio button not gray? It's should be active. Active - Blue.
<img width="706" alt="2016-06-20 12 23 01" src="https://cloud.githubusercontent.com/assets/2894860/16189190/c45cab10-36e1-11e6-8105-5e9fbe735935.png">

**Comment by vades** [comment]
1. I have removed "disabled" status for selected radios with text input.
2. _Why in case on picture radio button not gray?_
A radio button is a native element specific to each OS/browser. There is no way to change it's color/style with CSS, unless you want to implement custom images or use a custom JS library.

**Comment by aivs** [comment]
I mean Gray as Inactive.

**Comment by PoltoS** [comment]
@aivs is it fixed?

**Comment by vades** [comment]
Labeled with yellow "testme" are already fixed

**Comment by aivs** [comment]
Tested, all ok.
