### ISSUE TITLE
Missing edit boxes in Configuration

### ISSUE THREAD

**Issue by bogri** [Z-Wave-Me/ExpertUI#176]
A lot of values can't be set in expert ui -> configuration -> configuration due to many edit boxes missing. Aeon Multisensor 6, z-way 2.2.0.
![config](https://cloud.githubusercontent.com/assets/17220050/13028675/0e2c0ffe-d276-11e5-84fa-8980ea26038e.png)

**Comment by PoltoS** [comment]
Duplicate to #50
