### ISSUE TITLE
Door Lock Set Timeout Problem

### ISSUE THREAD

**Issue by zwave-mke** [Z-Wave-Me/ExpertUI#177]
Configuration Set Timeout Problem.

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://192.168.10.182:8083/ZWave.zway/Run/devices[5].instances[0].commandClasses[98].ConfigurationSet(1,1)

**Comment by PoltoS** [comment]
Please check, it was certainly fixed in April during Z-Way@DuneHD certification

**Comment by vades** [comment]
Duplicate: https://github.com/Z-Wave-Me/ExpertUI/issues/238
