### ISSUE TITLE
Battery Icon Update Problem

### ISSUE THREAD

**Issue by zwave-mke** [Z-Wave-Me/ExpertUI#179]
When you press the update battery Button, then the Value is Updated but not the ICON and the "%" is lost.

**Comment by pz1** [comment]
This phenomenon has been around longer. After a while the % sign appears again. I did interpret that to signify that a new value was obtained

**Comment by vades** [comment]
Fixed

**Comment by aivs** [comment]
Not works, need page reload.

**Comment by vades** [comment]
And what's exactly not working? On my site works fine.Can you please provide more detailed information or a screenshot?
