### ISSUE TITLE
In Interview results dialog run interview on the corresponding channel

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#181]
Currently interview runs on the instances[0] always - even if clicked on channel №4

![buginstance](https://cloud.githubusercontent.com/assets/3664383/13193249/7651a6ba-d786-11e5-8f92-c34d9fd38ab7.png)

**Comment by aivs** [comment]
Force interview not works. "undefined" instead Instance number and command class 
<img width="1280" alt="2016-06-15 19 16 49" src="https://cloud.githubusercontent.com/assets/2894860/16088112/43b6d30c-332e-11e6-8030-c47d785b9687.png">
