### ISSUE TITLE
Wrong handling of Expert Commands prototypes

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#184]
The code below that handles Expert commands is wrong.

1) Instead of serializeArray you shoul walk through all rendered params and check which radiobutton is selected to pick up from the correct input field the value
2) it is wrong to skip "" values [ (v.value === '') ], since string field can be valid with "".
3) it is not valid to detect type of value via isNaN [ if (isNaN(v.value) ], since string value "01234" will be errorneous converted into numer 1234 and sent as integer (without leading 0). Instead you should walk through all params and take their types based on original types used to render the form.

./app/core/controllers/configuration.js:

```
$scope.submitExpertCommndsForm = function(form, cmd) {
        //var data = $('#' + form).serialize();
        var data = $('#' + form).serializeArray();
        var dataJoined = [];
        angular.forEach(data, function(v, k) {
             if (v.value === '') {
                return;
                //dataJoined.push('\'\'');
            }else{
                if(isNaN(v.value)){
                     dataJoined.push('\'' + v.value + '\'');
                }else{
                    dataJoined.push(v.value); 
                }
            }

        });
```

**Comment by vades** [comment]
- Now is an empty value send.
- Numbers ar send without quotes.
- Other values are send with "quotes"
