### ISSUE TITLE
No device description selected for Aeotec Smart Switch 6

### ISSUE THREAD

**Issue by bogri** [Z-Wave-Me/ExpertUI#185]
The "Device description" is selected in "Interview" tab and the product is then shown as:

Product     Smart Switch 6 EU

but switching to "Configuration" tab just shows:

"No device description selected. You can select device description from the tab "Interview""

Device: Aeotec Smart Switch 6 (ZW096-C16)
Z-way Version number:   v2.2.1
Razberry as controller

**Comment by PoltoS** [comment]
May be this file contains no Configuration description? We need to know ZDDX file name to have a look.

**Comment by bogri** [comment]
Ok, but I don't understand. If I click "Select Device Description" there is an option in the drop down that says "Aeon Labs Smart Switch 6", which I chose. Grep for "Smart Switch 6 EU" gives me:

722-0086-0003-0060-03-04-05-00-63.xml

**Comment by PoltoS** [comment]
Are you sure your selection was applied? Do you see a picture of your plug after choosing it?

**Comment by bogri** [comment]
Yes, totally sure - it's set. I can see the picture of the plug. See attached pic.
![plug](https://cloud.githubusercontent.com/assets/17220050/16059551/a49fee34-3283-11e6-9feb-da3bdacd1448.png)

**Comment by PoltoS** [comment]
I don't see any reason for the problem, so either give us remote access, please.

We will also try to reproduce it.

**Comment by aivs** [comment]
try Chrome or Chromium

**Comment by bogri** [comment]
I tried Chrome and Opera but same problem. I can choose whatever description and the pic shows up, but switching to "Configuration" gives the same result.

**Comment by bogri** [comment]
Still no news about this one? Now upgraded to v2.2.4, and the same behaviour. Can it have something to do with the "Z-Way hack to make the Smart Switch 6 work as a ON/OFF switch" described on Aeotec support site?

**Comment by zwave-mke** [comment]
Hi, maybe device-description is to old.
