### ISSUE TITLE
Wrong Sensor data

### ISSUE THREAD

**Issue by Marko1704** [Z-Wave-Me/ExpertUI#186]
Hi,
I have a problem with the Sensor Values. 5 times in the last 3 days I had a problem when on the Controll > Sensor, there was the wrong Number displayed. This number was also impossible to update and the Value was correct again after the Interview was forced. I also checked Configuration > Experts Commands  and I noticed that the scale was different that It was when the module was included. I managed to catch the data sent from the module, so that I can be positive that the module sends the correct value.
Please find attached the pdf document with print screens and the LOG file
Best regards
Marko
[30-3-2016_Z-Wave-me.pdf](https://github.com/Z-Wave-Me/ExpertUI/files/195377/30-3-2016_Z-Wave-me.pdf)

[Z-Wave_me_30-03-2016.txt](https://github.com/Z-Wave-Me/ExpertUI/files/195365/Z-Wave_me_30-03-2016.txt)

**Comment by PoltoS** [comment]
Your log contains no debug info. Please set in config.xml logging to debug. Also please try new v2.2.2 - there were few bugs fixed, I think this one is fixed too. If you confirm the bug to be still here, please open new issue with console log in debug more. It will be great to compare zniffer trace with console log together.
