### ISSUE TITLE
Wrong frequency string

### ISSUE THREAD

**Issue by vades** [Z-Wave-Me/ExpertUI#188]
Button frequency in the  Network/Controll sends wrong frequency string on first click. The second click sends correct string.

**Comment by vades** [comment]
I've tested and can't reproduce this error. Can you provide more informations: screenshot, command ...

**Comment by PoltoS** [comment]
Are you talking to yourself ? ;) the issue is from you ;)

This is a backend problem, I'll fix it.

**Comment by vades** [comment]
Looks like I'm talking to myself :-)
