### ISSUE TITLE
Unable to set ZDDX

### ISSUE THREAD

**Issue by liollury** [Z-Wave-Me/ExpertUI#189]
I want to set device descriptor on a FGRM222 but it tell me 

> Error handling data/ZWave.zway/Run/devices[9].LoadXMLFile("492-010f-0301-1001-03-03-34-16-16.xml")

and i've got a 500 internal server error : 
**POST http://192.168.0.5:8083/ZWave.zway/Run/devices[9].LoadXMLFile(%22492-010f-0301-1001-03-03-34-16-16.xml%22)** 

> SyntaxError: Unexpected token %

**Comment by liollury** [comment]
It works if I restart myself POST request with ' and not " :
http://192.168.0.5:8083/ZWave.zway/Run/devices[9].LoadXMLFile('492-010f-0301-1001-03-03-34-16-16.xml')
instead of:
http://192.168.0.5:8083/ZWave.zway/Run/devices[9].LoadXMLFile("492-010f-0301-1001-03-03-34-16-16.xml")

**Comment by PoltoS** [comment]
This was fixed: https://github.com/Z-Wave-Me/z-way-issues/issues/107#issuecomment-223456462
