### ISSUE TITLE
Bug in 2.2.2 test new web server

### ISSUE THREAD

**Issue by jschn66** [Z-Wave-Me/ExpertUI#190]
I have tried Version v2.2.2-test-new-webserver-0-g000000 and Version v2.2.2-test-new-webserver-5-gba57763 on raspberry pi 3 B, jessie, razberry.
I have installed the same files on raspberry pi 1 B - same problems. 
If i select device in "select device description" in expert UI then i get always "XML-Error".
Version v2.2.2 works fine.

**Comment by PoltoS** [comment]
Duplicate to https://github.com/Z-Wave-Me/z-way-issues/issues/107

**Comment by PoltoS** [comment]
New v2.2.2-test-new-webserver-8-ga9cd319 should fix the problem
