### ISSUE TITLE
Error Handling Data - LoadXMLFile

### ISSUE THREAD

**Issue by cmolnar65** [Z-Wave-Me/ExpertUI#191]
Error handling data
/ZWave.zway/Run/devices[27].LoadXMLFile("684-014f-4744-3530-03-04-05-00-7a.xml")

1. From Expert Mode select the device configuration.
2. Attempt to set device description

![2016-06-01_15-57-03-1](https://cloud.githubusercontent.com/assets/10200860/15723708/c4aaf6aa-2811-11e6-8b08-3f9363f8afdb.png)
![2016-06-01_15-57-16-2](https://cloud.githubusercontent.com/assets/10200860/15723710/c6e4fc18-2811-11e6-8c71-9e3bdb424b44.png)
![2016-06-01_15-57-28-3](https://cloud.githubusercontent.com/assets/10200860/15723715/c9d3f0d2-2811-11e6-925a-385d33fa5697.png)

**Comment by PoltoS** [comment]
What version of Z-Way is it? Are you using test version made to test new web server?

**Comment by cmolnar65** [comment]
Whatever version installed per the directions on the main website for new users using:

wget -q -O - http://razberry.z-wave.me/install | sudo bash

the Changelog shows:

11.04.2016 v2.2.2

Which believe it or not seems to have installed v2.2.2-test-new-webserver according to the UI.

**Comment by PoltoS** [comment]
There was a missing char in file name, so it used this test version as latest. Now fixed. Pleas re-install again to the v2.2.2 (or use Settings->Maintenance->Firmware upgrade).

The bug will be closed, since we move it in another issue tracker https://github.com/Z-Wave-Me/z-way-issues/issues/107

**Comment by PoltoS** [comment]
New v2.2.2-test-new-webserver-8-ga9cd319 should fix the problem
