### ISSUE TITLE
Select Device Description not working

### ISSUE THREAD

**Issue by noctoz** [Z-Wave-Me/ExpertUI#192]
I get the following error (or some version of it) for all devices with latest version:

Error handling data
/ZWave.zway/Run/devices[7].LoadXMLFile("641-0159-0003-0002-03-03-1c-01-0c.xml")"

This happens to at least one other user:

http://forum.z-wave.me/viewtopic.php?f=3422&t=23322&sid=6076e58a870e82296b69e8ade0e20bcf

**Comment by PoltoS** [comment]
Duplicate to https://github.com/Z-Wave-Me/z-way-issues/issues/107

Please install latest (v2.2.2) to get stable version

**Comment by PoltoS** [comment]
New v2.2.2-test-new-webserver-8-ga9cd319 should fix the problem

**Comment by KJTamas** [comment]
When will the windows version is available?

**Comment by PoltoS** [comment]
New 2.2.3-rc2 for Windows is online

**Comment by KJTamas** [comment]
New version is not working. "There is no device installed yet". I upgraded from 2.2.2 test new webserver 5. This version (2.2.2) is worked.

**Comment by PoltoS** [comment]
What is new webserver 5?

**Comment by KJTamas** [comment]
http://razberry.z-wave.me/z-way-server/z-way-server-windows-v2.2.2-test-new-webserver-5-gba57763.msi
Build 22-may-2016

**Comment by PoltoS** [comment]
Please try the one I mentioned yesterday.

2.2.3-rc2

**Comment by KJTamas** [comment]
I tried that, but it did not work. No error messages in zway log file. I set logging level to 0, and restarted the service. Created a big log file (571KB), but i can't find any error messages. No error in event log too.
If you think, i can upload log files (compressed 32KB) somewhere.
