### ISSUE TITLE
All associations looks like not selected in UI

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#194]
A few month ago all associations took the gray color. Now after adding new device, z-way is gray, but if add another device to associations it's blue. 
<img width="1158" alt="2016-06-15 19 55 19" src="https://cloud.githubusercontent.com/assets/2894860/16089505/127a9494-3334-11e6-9b20-e5f9e10108d0.png">

**Comment by zwave-mke** [comment]
Hi, just load assoc-groups from device.

**Comment by PoltoS** [comment]
Will re-open. @aivs will add more details. This page requires more work anyway

**Comment by vades** [comment]
Is caused by https://github.com/Z-Wave-Me/ExpertUI/issues/225
