### ISSUE TITLE
Qubino interview problem

### ISSUE THREAD

**Issue by noctoz** [Z-Wave-Me/ExpertUI#195]
I have a problem with completing the interview for my qubino relays.
See this thread: http://forum.z-wave.me/viewtopic.php?f=3422&t=23427

**Comment by theBuga** [comment]
I have the same problem. The two 'Version' interviews fail.

*) Device Info: see attached screenshot
![device info](https://cloud.githubusercontent.com/assets/24698466/21392444/2c2e7928-c790-11e6-8b95-ccf8dc728dc6.jpg)

*) Controller Info: see attached screenshot
![z-way version info](https://cloud.githubusercontent.com/assets/24698466/21392458/42e47492-c790-11e6-9918-65756573fcfc.jpg)

*) Linux/Raspbian:
/bin/ls: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=5e052e8de057d379ab51d4af510ad9318fe77b46, stripped
Linux raspberrypi 4.4.27-v7+ #917 SMP Tue Oct 25 16:00:29 BST 2016 armv7l GNU/Linux

*) log file: attached
[z-way-server.txt](https://github.com/Z-Wave-Me/ExpertUI/files/666527/z-way-server.txt)

**Comment by zwave-mke** [comment]
Hi, problem is known and scheduled for backend.

**Comment by PoltoS** [comment]
Problem fixed. We will make an RC soon with the fix. Please keep updated.
