### ISSUE TITLE
Can't set 2 radio button together in different labels for one command class form

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#196]
To control AV I use Remotec ZXT-310. Set command for command class SimpleAVControl has 2 parameters: Key attribute and Button, I need to set it together, but I can't, because when I set radio button in Button list, in Key attribute list radio button becomes unset.
It's a bug, both lists has a same name of input name:
`<input name="Set"`

<img width="1280" alt="2016-06-29 17 03 54" src="https://cloud.githubusercontent.com/assets/2894860/16455353/a5b9d0d8-3e1c-11e6-8805-c06ff131d243.png">
<img width="1280" alt="2016-06-29 17 03 17" src="https://cloud.githubusercontent.com/assets/2894860/16455350/a4b19130-3e1c-11e6-94e5-2e7d9bc1e0ce.png">

**Comment by aivs** [comment]
At this moment from UI it's not possible to control ZXT-310

**Comment by vades** [comment]
This is caused by https://github.com/Z-Wave-Me/ExpertUI/issues/229
