### ISSUE TITLE
v2.2.3 (2016-07-12)  Expert > Timing Info Error

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#197]
Under Network >Timing Info I consistently (after ZWay restart) get message: `Error handling data from server` and no information on the screen. 
My configuration RaspiB/RaZberry - Jessie lite Feb 2016

Same occured on my  Raspi2/UZB1 - Jessie lite Feb 2016

**Comment by rbrlibero** [comment]
there is a way to downgrade ?

**Comment by PoltoS** [comment]
sure, you can downgrade or wait for us to fix it very soon

**Comment by pz1** [comment]
I don't think it is a good policy to close issues before they are fixed and verified

**Comment by PoltoS** [comment]
It is verified internally. Agree, you have not verified it.  Now there is an 2.2.4-rc2 that should have this fixed

**Comment by pz1** [comment]
Thanks.
Installed 2.2.4-rc2 on the offending machine. Timing info is indeed no longer producing errors
