### ISSUE TITLE
No display for the AlarmSensor CC

### ISSUE THREAD

**Issue by NilsBohr** [Z-Wave-Me/ExpertUI#2]
There is no display of any devices with the AlarmSensor CC in the old "blue" UI. It is critical for Fibaro Smoke Sensor, because this device doesn't have any Sensor Binary CC. This means We can't see, when it senses smoke.

Please add it in the new Expert UI
![image](https://cloud.githubusercontent.com/assets/5468659/4235152/238aaa3e-39bd-11e4-9ebb-f9e6bd214677.png)

![image](https://cloud.githubusercontent.com/assets/5468659/4235159/3764d94e-39bd-11e4-9626-9038799db2e6.png)

![image](https://cloud.githubusercontent.com/assets/5468659/4235170/52421722-39bd-11e4-9d82-bcbacae8695b.png)

**Comment by vades** [comment]
Section sensors now displays AlarmSensors (instance.commandClasses[0x9c])
