### ISSUE TITLE
security interview a lot of times not complete 

### ISSUE THREAD

**Issue by rbrlibero** [Z-Wave-Me/ExpertUI#202]
A lot of times security interview in not complete and a  notifications were generated 
there is a way to disable security after pairing ?

**Comment by klaasjoerg** [comment]
Having the same issue. Even on same types of devices e.g. Fibaro WallPlugs. 
So, would be interested to also get an answer on this (strange) behaviour...

**Comment by zwave-mke** [comment]
Hi, problem is known, move device closer to controller.

**Comment by klaasjoerg** [comment]
Yes found out already. But is it possible to force unsecure out inclusion? Or change it to unsecure without excluding again?

**Comment by PoltoS** [comment]
No, you must exclude-include
