### ISSUE TITLE
UZB f/w update should go to z-wave.me link and use HTTPS

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#204]
Becasue while working via find.z-wave.me (uses HTTPS) HTTP content is not loaded by browser: 'https://find.z-wave.me/expert/#/uzb' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint. This request has been blocked; the content must be served over HTTPS

**Comment by vades** [comment]
Already replaced
