### ISSUE TITLE
Error when setting Wake up time for StellaZ thermostatic device

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#206]
When I try in menu configuration/configuration to save/set the wakeup time of my StellaZ TRV's to for example 960 seconds, after the warning message that the device must be woken up,  I do get the following error message: 

![setwakeup](https://cloud.githubusercontent.com/assets/7747627/17553830/27c67ebc-5f08-11e6-8e26-d97764621fdd.PNG)

It looks as if it tries to set 9601. Of course nothing goes to queue or log. Observed with v2.2.4-rc2, but I vaguely remember having seen this before.

**Comment by pz1** [comment]
Similar problem occurs in v2.2.4-rc9 if I try to set wake-up time to  86400

**Comment by PoltoS** [comment]
@vades please fix it. It is a simple one, but annoying

**Comment by pz1** [comment]
Checked with v2.2.4-rc20. First attempt gave the original error. Tried again on the same device no error then. Subsequet tries on other StellaZ devices did not produce any errors in the interface. So I assume it is fixed.
