### ISSUE TITLE
Wrong Time

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#208]
Expert UI used time of my OS, not Raspbian time. In OSX I set wrong time, and Expert UI showed this time.
SmartHome UI used Raspbian system time and it's ok.
![2016-08-29 17 21 37](https://cloud.githubusercontent.com/assets/2894860/18054570/1f35b43e-6e0d-11e6-83b1-200c443b6fc0.jpg)

**Comment by vades** [comment]
Expert now uses same API as SmartHome
