### ISSUE TITLE
Smal inconsistency on home page

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#209]
This is a minor issue, that may confuse some new users. At the end of the text of ExpertUI home page there is a reference to the manual:

> ![link](https://cloud.githubusercontent.com/assets/7747627/18271231/5783707c-7431-11e6-87e2-b058a73780b6.PNG)

The hyperlink with name www.z-wave.me on this page actually refers to http://razberry.z-wave.me/. Some users could choose to type www.z-wave.me. That site has a different, but also useful, set of links.
_update 20161022: Stil problem in v2.2.4_

**Comment by pz1** [comment]
@PoltoS: Feel free to close this issue if you think it is irrelevant

**Comment by PoltoS** [comment]
9a6ef15

**Comment by PoltoS** [comment]
@pz1 Thanks!
