### ISSUE TITLE
Discrepancy in number of devices between ExpertUI and SmartHome

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#210]
This morning at the inclusion of a Popp 004001 Smoke Detector, I did notice that the list of supported Popp devices that I could choose from in SmartHome is longer than the ones I can select in ExpertUI.

I had expected that both interfaces were using the same source. That does not seem to be the case. Why?

**Comment by PoltoS** [comment]
Expert UI is not showing Alarm CC, AlarmSensor CC and some others. Worth to add in future, but this is minor as this UI is not for control.

**Comment by pz1** [comment]
My concern is not about control!
The point is that a user can either include a new device using SmartHome or include via Expert UI.
Smarthome presents more Popp Smoke detector devices than EUI does. That bears the risk of choosing the wrong device for configuration.

**Comment by PoltoS** [comment]
The number of devices in SH should be same and should not depend on from where you include it.

**Comment by pz1** [comment]
In v2.2.4rc16, EUI has 6 various devices including sensors; SmartHome had 6 different wall plugs, but no sensors.

**Comment by zwave-mke** [comment]
Hi, we will add a another tab for alarm CC in one of the next releases.
