### ISSUE TITLE
Error on license tab

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#211]
Please replace in htdocs/expert/app/core/build.js, line 40053
            $scope.controllerIsZeroUuid = parseFloat(ZWaveAPIData.controller.data.uuid.value) === 0;
to
            $scope.controllerIsZeroUuid = parseInt("0x" + ZWaveAPIData.controller.data.uuid.value, 16) === 0;

**Comment by vades** [comment]
Fixed
