### ISSUE TITLE
v2.2.4rc-18: ExpertUI Configuration-Expert  Commands not shown

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#212]
Expert commands screen is distorted

![expert](https://cloud.githubusercontent.com/assets/7747627/19148490/4682371a-8bbd-11e6-830b-8563c9664b6b.PNG)
Tested on RaspiB/Razberry Gen3 Rasbian Jessie

**update**: problem still exists on rc19 (I assume that one was released after this message) I will test with next version

**Comment by vades** [comment]
Fixed

**Comment by pz1** [comment]
Correct in rc20!
