### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by BrianAker** [Z-Wave-Me/ExpertUI#213]
Can you add a LICENSE file to the project?

Is it Apache 2.0, GPL, proprietary?

Thanks!

**Comment by PoltoS** [comment]
Expert UI is under GPL. We are too lazy to add it, but it is even scheduled, we will do it!

**Comment by PoltoS** [comment]
@vades Please add GPL V3 license to all files in this project, in Smart Home

@zwave-mke Marcel, approved?
