### ISSUE TITLE
Error in configuration of 101, 102 etc

### ISSUE THREAD

**Issue by mebj** [Z-Wave-Me/ExpertUI#214]
I tried to configure an Aeon Multisensor v1.18 with the Expert UI and ticking more than 1 option for group 101  (there are 4 options i.e. battery, temperature, humidity and luminance) is impossible and immediately renders an error. Also once battery option is set it is impossible to remove it.

Only way around was go to the "Expert" function and set item 101 to 225.
Before figuring out how to set this the Multisensor did not send any info but monitored movements.
The Z-Way installation is brand new (from today 2016-11-02) and the controller is a brand new 
RaZberry2 EU Gen5. The Pi is a Pi2 with a Jessie installation.

There are also quite a few other errors like when using "get" I do not get any info in the text boxes.
Browsers tested were IE, Firefox and Chrome all on Win 10.

**Comment by zwave-mke** [comment]
hi, not a problem of expert-ui, its a problem device description file from zwave alliance, please use generic configuration dialog.
