### ISSUE TITLE
Device disappears from Configuration list if used only one channel. The other channels is not available

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#216]
I tried to control Fibaro RGBW with KFOB: 1 button - 1 channel, 2 button - 2 channel, 3 button - 3 channel, 4 button - 4 channel. I added 1 channel into 1 group, applied the settings, now Fibaro RGBW was gone from configuration list, so I can't configure other channels.

**Comment by vades** [comment]
Is caused by: https://github.com/Z-Wave-Me/ExpertUI/issues/225
