### ISSUE TITLE
Water Meters are not shown in the list of Meters

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#217]
This is due to this string: https://github.com/Z-Wave-Me/ExpertUI/blob/46ea9810536a14673e26a2160b3d1194dc55d06a/app/core/controllers/meter.js#L76

Why is this?

**Comment by PoltoS** [comment]
Also meters on different channels (0 and 1) mixes their values on press of Update button. Any idea?

**Comment by vades** [comment]
Should I remove this:
if (meter.sensorType.value > 1) {
                            return; //  gas and water have real meter scales
                        }

**Comment by PoltoS** [comment]
I don't know why was this introduced in the code, so not sure if just removing it will not harm in some other place. Please check it (I believe this was written by you ;)

@zwave-mke
