### ISSUE TITLE
Add file field for UZB Firmware/Bootloader update

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#218]
The backend side is done here:
https://github.com/Z-Wave-Me/home-automation/commit/ef90f41bba6bb9c6ef7ff778aefc205dfb389197

**Comment by vades** [comment]
Can you be more specific about "How to add file field..."?

**Comment by PoltoS** [comment]
Below the list of f/w available from the server please add a File selector + Button to send a /bin file from local disk.
