### ISSUE TITLE
Not Configuration and Assocoation tabs in expertUI. v2.3.0-rc7

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#222]
<img width="1280" alt="2017-01-19 23 49 13" src="https://cloud.githubusercontent.com/assets/2894860/22124729/13ab9f1a-dea2-11e6-99dc-8ae6a1fae519.png">
<img width="1280" alt="2017-01-19 23 49 16" src="https://cloud.githubusercontent.com/assets/2894860/22124730/14ac24d4-dea2-11e6-97bf-3d23805056b2.png">

**Comment by PoltoS** [comment]
Fixed
