### ISSUE TITLE
Set language error

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#226]
When I'm trying to change language from Russian to English appears a error message.
<img width="1280" alt="a2a33644-e878-11e6-9be3-d1a6ebb57b69" src="https://cloud.githubusercontent.com/assets/2894860/22505356/22100188-e88c-11e6-95d4-7eb3c38d61e0.png">

**Comment by jnissen** [comment]
Same from English to Germany

**Comment by aivs** [comment]
If press "No", language successfully changed
<img width="1280" alt="2017-02-18 17 22 11" src="https://cloud.githubusercontent.com/assets/2894860/23093868/3218b8c4-f5ff-11e6-8e9e-0b7ded13300e.png">
