### ISSUE TITLE
Not shown Configuration if UI language not EN. Not button to choose ZDDX

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#227]
My language Russian. I choose ZDDX file without Russian translate, only English. In Configuration I see nothing, I was expecting to see the settings in English. 
And where button "Choose description file"  on Configuration tab ?
<img width="1280" alt="2017-02-01 12 22 22" src="https://cloud.githubusercontent.com/assets/2894860/22501478/086c366e-e87a-11e6-9d9f-9b6b6e9bd741.png">
<img width="1280" alt="2017-02-01 12 22 18" src="https://cloud.githubusercontent.com/assets/2894860/22501481/0b5af2b6-e87a-11e6-8a6b-46cdbf57b294.png">

**Comment by zwave-mke** [comment]
done?

**Comment by vades** [comment]
Issues with label "testme" are ready for testing.

**Comment by aivs** [comment]
Now able to set a russian name, but why new name displayed only in Device Name field, why in left list the device still has the old name? Need page refresh to display the name correctly everywhere.

**Comment by aivs** [comment]
Settings appeared
<img width="1237" alt="2017-05-15 14 47 53" src="https://cloud.githubusercontent.com/assets/2894860/26056356/a9e191fc-397d-11e7-85cf-99ae7adf0442.png">
