### ISSUE TITLE
Can't configure bitset parameters, it always 0

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#228]
I'm trying to configure bitset parameters, but when I press Apply, parameter set to 0.
<img width="1280" alt="2017-02-01 14 30 13" src="https://cloud.githubusercontent.com/assets/2894860/22505213/49a9eec6-e88b-11e6-9821-7d97a0b50a0a.png">

**Comment by vades** [comment]
Caused by: https://github.com/Z-Wave-Me/ExpertUI/issues/225
