### ISSUE TITLE
Expert commands with multiple parameters are wrong again

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#229]
Please!!!! Fix it again asap!

@zwave-mke 

![recorded](https://cloud.githubusercontent.com/assets/3664383/22532316/849dedb8-e8f7-11e6-948c-60bb5f705912.gif)

**Comment by aivs** [comment]
Tested. Not works.

**Comment by aivs** [comment]
Now it's possible! All ok!
<img width="1210" alt="2017-03-13 16 37 27" src="https://cloud.githubusercontent.com/assets/2894860/23856656/6c1374d8-080b-11e7-8d72-6f233187ef7c.png">
