### ISSUE TITLE
Need to select automatically dead device in list

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#231]
If list of dead devices not empty, need to automatically select first device. User will see that the list is not empty. Now it looks empty.

<img width="1280" alt="2017-02-02 12 59 24" src="https://cloud.githubusercontent.com/assets/2894860/22544855/9529396c-e947-11e6-9c58-f85f6340e479.png">

**Comment by PoltoS** [comment]
Bad idea - can lead to accidentally removal of a device. Better to write "select" in the empty element or leave as is

**Comment by aivs** [comment]
Agree
