### ISSUE TITLE
Can't choose second usbStick

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#233]
I have 2 usb sticks started, but in expert ui I see only one
<img width="1280" alt="2017-02-03 18 17 39" src="https://cloud.githubusercontent.com/assets/2894860/22596570/28aeab04-ea3d-11e6-822d-55ebc6d02a3b.png">

**Comment by PoltoS** [comment]
/JS/Run/ZWave.list() reports two elements

**Comment by vades** [comment]
Dongle select is shown when:
- Response from http://IP:8083/ZWave/list  contains an array with lenghth > 1
["zway","zway2"]
![dongle](https://cloud.githubusercontent.com/assets/1451741/23653612/7c146398-032d-11e7-93d9-be658e93d896.png)

["zway"] 
![dongle2](https://cloud.githubusercontent.com/assets/1451741/23653621/8272de72-032d-11e7-90eb-34f88a0fc219.png)

What do you get from API: http://YOURIP:8083/ZWave/list ?

**Comment by aivs** [comment]
Report two items
<img width="390" alt="2017-03-07 14 05 22" src="https://cloud.githubusercontent.com/assets/2894860/23653885/4b817556-033f-11e7-97c2-068a7e1c4861.png">
<img width="825" alt="2017-03-07 14 05 39" src="https://cloud.githubusercontent.com/assets/2894860/23653889/505c118a-033f-11e7-8985-d4382bd40f59.png">
<img width="768" alt="2017-03-07 14 06 14" src="https://cloud.githubusercontent.com/assets/2894860/23653891/5564acbe-033f-11e7-9a3b-f4ce2c0a2baf.png">

**Comment by vades** [comment]
Looks like you have old version of UI. This bug is already 1 month fixed. Try to update to latest firmware v2.3.1-rc2

**Comment by aivs** [comment]
Ok, I installed v2.3.1-rc3, it contained the same expert UI version 1.2, so bug presents.
**MASTER**
<img width="915" alt="master" src="https://cloud.githubusercontent.com/assets/2894860/23658956/878017a4-0355-11e7-8239-36c74e246f95.png">
Then I got expert UI from git dev
**DEV**
<img width="984" alt="dev" src="https://cloud.githubusercontent.com/assets/2894860/23658967/97dc44a6-0355-11e7-9449-969afd2a9884.png">
And tested git stage
**STAGE**
<img width="567" alt="stage" src="https://cloud.githubusercontent.com/assets/2894860/23659000/b67b5456-0355-11e7-86de-fa1f9da3179e.png">

The result is same
<img width="415" alt="2017-03-07 16 40 17" src="https://cloud.githubusercontent.com/assets/2894860/23659012/c5abbaf6-0355-11e7-8d6b-58ec8dd4a682.png">
<img width="920" alt="2017-03-07 16 40 27" src="https://cloud.githubusercontent.com/assets/2894860/23659018/ca962646-0355-11e7-90e1-ce5eef2134cb.png">

**Comment by vades** [comment]
OK, thanks for info. On my site it works. Do you have some error in the Browser console?

**Comment by vades** [comment]
I got it. I tested two nongles in the wrong place :-)

**Comment by aivs** [comment]
Works!
<img width="1280" alt="2017-03-09 13 32 54" src="https://cloud.githubusercontent.com/assets/2894860/23746462/fee769b4-04cc-11e7-8345-c0b89492c052.png">
