### ISSUE TITLE
Can't rename device. Error appears 

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#234]
<img width="1280" alt="2017-02-09 14 33 45" src="https://cloud.githubusercontent.com/assets/2894860/22781727/e67af57a-eed4-11e6-8239-d70ab2cd1290.png">

**Comment by aivs** [comment]
<img width="1280" alt="2017-04-02 19 30 07" src="https://cloud.githubusercontent.com/assets/2894860/24588966/059b155a-17db-11e7-97c3-b17cc53fda6c.png">

in 2.3.1 doesn't work

**Comment by vades** [comment]
1. Are there special characters in the name?
2. What for error is in your  error log?

**Comment by vades** [comment]
I explored it and the result is:
Some chars are replaced with "?" E.G.: ü, ö, ä 
![utf](https://cloud.githubusercontent.com/assets/1451741/24598742/560b60e0-184d-11e7-9c6f-122de31d419d.png)

Some characters E.G: "ß" produces 500 Internal Server Error: 
![utf-1](https://cloud.githubusercontent.com/assets/1451741/24598747/5d8a4a5c-184d-11e7-932e-d8b5fc10fe58.PNG)

Back-end do not accepts some special character in Device Name. This need a fix on th back-end

**Comment by ronie-z-wave** [comment]
@aivs @PoltoS this is more z-way relevant right?

**Comment by aivs** [comment]
Test with russian symbols:
Привет из России!

**Comment by ronie-z-wave** [comment]
Grüße aus Deutschland! :D

Does your russian example work?

**Comment by PoltoS** [comment]
This works: http://192.168.0.32:8083/JS/Run/zway.devices[1].data.givenName="Привет из России!"

But same via UI does not.
![givenname](https://cloud.githubusercontent.com/assets/3664383/24655094/61a50ce6-1945-11e7-8788-2f0096b63ea2.png)

Looks like you use some Unicode (UTF16?) conversion, while you should not. UTF8 should be used.

Here is a proof that backend can also welcome you in your mother language :) 
![givenname 2](https://cloud.githubusercontent.com/assets/3664383/24655136/a29f17fa-1945-11e7-91c0-e14560d98016.png)

**Comment by ronie-z-wave** [comment]
ok ... Martin supposes POST via URL could be the problem ... he'll change this

**Comment by vades** [comment]
I replaced function escape(deviceName) with encodeURIComponent(deviceName) and seems to works:
RU lang
![encoding-ru](https://cloud.githubusercontent.com/assets/1451741/24695380/d1d79b82-19e5-11e7-9b5b-ab6f06b429b2.png)

DE spec chars
![encoding-de](https://cloud.githubusercontent.com/assets/1451741/24695393/df5c9c3a-19e5-11e7-9096-4400f00a800d.png)

This can solve the problem in UI

**Comment by aivs** [comment]
Now able to set a russian name, but why new name displayed only in Device Name field, why in left list the device still has the old name? Need page refresh to display the name correctly everywhere.
<img width="1230" alt="2017-05-15 14 30 01" src="https://cloud.githubusercontent.com/assets/2894860/26056228/1c8f6a7c-397d-11e7-9e51-6d7b248ddcf7.png">

**Comment by zwave-mke** [comment]
still need page-reload to see the new name

**Comment by vades** [comment]
This is already fixed

**Comment by aivs** [comment]
done
