### ISSUE TITLE
On language change answering "yes" on "Change date and time format" leads to "ERROR. Unable to update data."

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#235]

**Comment by aivs** [comment]
I press No, but language anyway changed.

**Comment by vades** [comment]
Language will be changed if you click on YES or NOT. These buttons are for timezone settings:
**Change date and time format to chosen language or keep current settings?**
I agree that the text is not well formulated.

**Comment by aivs** [comment]
"No" means don't apply settings

**Comment by vades** [comment]
"No" means: don't change date and time format

**Comment by aivs** [comment]
ok, why this window appears if I didn't change the date and time format?

**Comment by vades** [comment]
Provider requirements

**Comment by PoltoS** [comment]
Text changed?
