### ISSUE TITLE
<br/> on queue window

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#236]
![2017-02-10 15 27 12](https://cloud.githubusercontent.com/assets/2894860/22826852/a301f1fa-efa5-11e6-9db7-8def67b7300e.png)

**Comment by vades** [comment]
Someone has embedded br tags in RU translation "inspect_queue_legend_help"
![queue_ru](https://cloud.githubusercontent.com/assets/1451741/22828684/f2aa27e2-ef9e-11e6-8b53-5729061ef274.PNG)
![queue_en](https://cloud.githubusercontent.com/assets/1451741/22828690/f948a1fa-ef9e-11e6-9a38-687257c65a89.PNG)
![queue_ru](https://cloud.githubusercontent.com/assets/1451741/22828691/f9699518-ef9e-11e6-9e87-1e806652e775.PNG)

**Comment by aivs** [comment]
9e05db7a638eeece6586fb6dbec9193d885ea0b0
