### ISSUE TITLE
Showed that interview is done, but really it's wrong

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#237]
![2017-02-10 15 33 17](https://cloud.githubusercontent.com/assets/2894860/22826986/769f9ada-efa6-11e6-8bbb-be17d13d1755.png)

**Comment by vades** [comment]
If something went wrong please describe what is wrong?

**Comment by aivs** [comment]
Interview showed 100%, but should be less. If one or more command classes not passed interview it anyway show 100%

**Comment by PoltoS** [comment]
Why closed? May be let @aivs confirm it?

**Comment by aivs** [comment]
I saw it once, couldn't reproduce

**Comment by vades** [comment]
We have found the bug and it is already fixed
