### ISSUE TITLE
Adding Associations not possible since 2.3.0

### ISSUE THREAD

**Issue by klaasjoerg** [Z-Wave-Me/ExpertUI#240]
Since my Update to 2.3.0. it's not possible to create new Basic Associations anymore.
I tried it with several battery devices (e.g. Coolcam Door/Window sensor) and woke up the devices a dozen times without any effect. The selected association device simply disappears again.

So I also tried it with mains powered devices (so to avoid any wake-up issues) and the effect is the same. 
Any idea how to solve this?

**Comment by klaasjoerg** [comment]
Quickly did another little test:
Setting associations doesnt work with Expert 1.2.0  so I downloaded and tried it with the previous version 1.1.0 where it works fine.

**Comment by devTechi** [comment]
Yes. I've got that problem too.

But I don't want to do a rollback if it isn't really necessary.

**Comment by klaasjoerg** [comment]
You don't need to do a full rollback. You can simply branch the old Expert-Part to get it this way working again.... as a temporary solution.

**Comment by devTechi** [comment]
Right. I know. I'll give it a try and download the _1.1.0_ release and replace the ui under `/opt/z-way-server/htdocs/epxert`

Thanks @klaasjoerg

**Comment by devTechi** [comment]
So I did the _downgrade_ but cannot test it, because I'm not physically around my devices. Will test it later.
Right now the behaviour is the same. The new association came up for a few seconds and gets deleted after that. But without waking up the device no association can be set.

Will report here later.

**Comment by devTechi** [comment]
It worked 👍 

Just had to wait for the device to wakeup. So with __v1.1.0__ it is working again.

**Comment by aivs** [comment]
At first, see description, interface of associations should works according this description:
ORANGE - Selected in UI but not active in device yet
GRAY - Active in device but not selected in UI
BLUE -Selected in UI and active in device

Problems:
1) All devices that added into association group become GRAY, should be BLUE.
2) All associations has exclamation mark, what this mean?
3) After adding new device into association group, it instantly disappears. Then I wake up device and device appears into association group. 

In fact, Association work, but ui works not correctly.

![default](https://cloud.githubusercontent.com/assets/2894860/23754647/ca7e74b6-04ee-11e7-81c7-295e0b4c75cf.gif)

**Comment by vades** [comment]
This happens because:
1. Info about associations are (should be) stored in the /config/Configuration.xml
2. If this file is missing assoc are not stored in configuration but only in the device:
3. If /config/Configuration.xml is present on your BOX then UI sends correct  request. API response is: 200 OK but Configuration.xml is not updated and is empty.
Because of this the ASSOC does not work correctly.
This have to be fixed in the backend API

**Comment by aivs** [comment]
I see the requests to Configuration.xml, but it empty.

<img width="1280" alt="2017-03-10 12 07 32" src="https://cloud.githubusercontent.com/assets/2894860/23789033/2ea00306-058a-11e7-9825-cb9bb159625b.png">

**Comment by vades** [comment]
This have to be fixed in the back-end API. Serguei?

**Comment by ronie-z-wave** [comment]
Please see also:
https://github.com/Z-Wave-Me/home-automation/issues/423
https://github.com/Z-Wave-Me/ExpertUI/issues/225

It is not working - maybe it's something that relies on webserver?

**Comment by PoltoS** [comment]
I confirm that the problem with POST of Configuration.xml is present. We try to nderstand from which version this started to find the porblem.

**Comment by aivs** [comment]
In 2.3.2 can't add Z-Way to associations

Want to add
<img width="1280" alt="2017-04-02 19 44 39" src="https://cloud.githubusercontent.com/assets/2894860/24589080/1f7a6c1c-17dd-11e7-80e4-e6441d64d168.png">

After 1 second Z-Way disappeared
<img width="1280" alt="2017-04-02 19 44 40" src="https://cloud.githubusercontent.com/assets/2894860/24589086/2d67d558-17dd-11e7-8514-b4ddc19fb52f.png">

**Comment by vades** [comment]
Because of https://github.com/Z-Wave-Me/ExpertUI/issues/225
See my comment:
This happens because..........

**Comment by Kosta-Github** [comment]
any news on this? I would really like to set/tweak some parameters of my devices...

**Comment by michaelhq** [comment]
same her with 2.3.6, any workaround or progress on this bug?

**Comment by zwave-mke** [comment]
tested on 2.3.7 and is working
