### ISSUE TITLE
'Include into Network" button disabled right after controller reset. It should be enabled

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#245]
Again....
Please finally fix it! Impossible to include self into another network

**Comment by ronie-z-wave** [comment]
please check your UI version

http://AMyBox:8083/cit/app/info.json`

it looks ok on my box with this UI version:
```
{
"name": "Z-Wave CIT",
"version": "1.2.0-RC-70",
"built": "01-03-2017 15:11:14",
"timestamp": "1488377474"
}
```

**Comment by PoltoS** [comment]
I use stage e115778ed219962e3d03796f761ec7888f4b1c5a

{
    "name": "Expert UI",
    "built": "27-01-2017 17:46:19",
    "timestamp": "1485535579"
}

**Comment by PoltoS** [comment]
Please merge those changes to stage

**Comment by PoltoS** [comment]
> I use stage e115778
as most clients do ;)

**Comment by ronie-z-wave** [comment]
Wir werden E-UI dev zweimal überprüfen, ob alles in Ordnung ist und wir werden es in der Bühne ASAP verschmelzen ;)

**Comment by PoltoS** [comment]
Sehr gut!
