### ISSUE TITLE
Z-Way name is wrong again

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#246]
https://github.com/Z-Wave-Me/ExpertUI/commit/c422040b87698a7b613f5b7d3ed0ebe4035fc883#diff-5d2cb5d930e367493fb06f62ce39d908R319

Please check that v.id == controller.nodeId.value and if so, use Z-Way/CIT name, otherwise v.name.

Please never rely on 1 - you never know the actual Id of Z-Way

**Comment by aivs** [comment]
I included Z-Way into HC2. The first device is still a Z-Way.
<img width="1280" alt="2017-03-09 16 20 44" src="https://cloud.githubusercontent.com/assets/2894860/23751977/9439a970-04e4-11e7-9a1e-73fb2953b345.png">
<img width="1280" alt="2017-03-09 16 00 51" src="https://cloud.githubusercontent.com/assets/2894860/23751984/9bfe1eca-04e4-11e7-8c0b-7d4a38e03514.png">

**Comment by vades** [comment]
Z-Way name is correct. Because of:
**...v.id == controller.nodeId.value and if so, use Z-Way/CIT**

**Comment by PoltoS** [comment]
Last time @aivs tested it (a week ago) it was still wrong. Have you tested it?

**Comment by vades** [comment]
**If nodeId = controller.nodeId.value  use Z-Way/CIT**
![controller-cit](https://cloud.githubusercontent.com/assets/1451741/24136990/fbf36098-0e11-11e7-9631-341dfef7bfbf.png)
![controller-zwave](https://cloud.githubusercontent.com/assets/1451741/24136991/fbf3d3a2-0e11-11e7-9b39-0b9c46628ec5.png)

**Comment by PoltoS** [comment]
I'm more concerned about another case - when Z-Way is secondary. It should show #1 as Device 1 (or by manufacturer name) and self ID as Z-Way

**Comment by zwave-mke** [comment]
this is solved
![zway_secondary](https://user-images.githubusercontent.com/9412970/28120347-112c16d0-6718-11e7-9435-8af7b99cf95d.png)

**Comment by zwave-mke** [comment]
closed
