### ISSUE TITLE
text on Settings tab is not aligned

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#249]
<img width="979" alt="2017-03-09 17 16 11" src="https://cloud.githubusercontent.com/assets/2894860/23753934/53a8bbd2-04ec-11e7-95b7-517a89f1db07.png">

**Comment by vades** [comment]
![settings-alligment](https://cloud.githubusercontent.com/assets/1451741/24044159/68ec42fa-0b1a-11e7-9c17-4bc3bf21d044.png)
