### ISSUE TITLE
Replace Device Db statement

### ISSUE THREAD

**Issue by christianpaetz** [Z-Wave-Me/ExpertUI#250]
The controller supports all certified Z-Wave devices in the market, namely those listed in the device data base http://pepper1.net/zwavedb/.

into

The controller supports all certified Z-Wave devices in the market.

**Comment by vades** [comment]
![home-text](https://cloud.githubusercontent.com/assets/1451741/25849845/66505f70-34c0-11e7-964a-5d59bd9bcfbc.png)

**Comment by PoltoS** [comment]
May be "on the market"?

**Comment by vades** [comment]
When you use "in" the market, you are talking about a product or company compared to others in that market.
If something is for sale, it is on the market.
IMHO " ...Z-Wave devices on the market"
See the:  https://ell.stackexchange.com/questions/17733/on-the-market-or-in-the-market

**Comment by zwave-mke** [comment]
done
