### ISSUE TITLE
Separate TW, KR, JP (and may be Singapore) from ANZ on the freq page

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#252]
(RaZ & CIT)

And I also propose to disable buttons not from this group to disallow switching to frequency on another range. In debug mode may be allow it.

@zwave-mke

**Comment by zwave-mke** [comment]
ok, agree

**Comment by ronie-z-wave** [comment]
done with https://github.com/Z-Wave-Me/ExpertUI/commit/eb70e06dba8bc80aa19d86995d69b2acc55eec25

**Comment by zwave-mke** [comment]
done

**Comment by PoltoS** [comment]
My idea was bad... After OTW of RaZberry or UZB we always get EU (even if the dongle is on US).

We will fix that in OTW process in next 5.23 f/w for UZB/RaZ, but meanwhile please let the support know that US and other countries might be affected.
