### ISSUE TITLE
Background RSSI uses wrong API path

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#256]
/ZWaveAPI/RSSI instead of stick specific /ZWave.zway1/RSSI

Please do never use /ZWaveAPI/ prefix - it is for backward compatibility only.

Check other API paths too

**Comment by PoltoS** [comment]
Same for ZNiffer function? Should it be per ZWave module instance?

**Comment by vades** [comment]
Now we have 2 types with APIs:
1. with dongle prefix eg: /ZWave.**prefix**/Restore
2. WITHOUT dongle prefix eg: /**ZWaveAPI**/RSSI
am I right??

To check other API paths too:
Can you please clarify, What API must be  with dongle and what APIs without dongle prefix.

**Comment by vades** [comment]
... and just tested:
/ZWaveAPI/Zniffer and /ZWaveAPI/RSSIGet are already used without dongle prefix. 
There is a list of the APIs with dongle prefix:
'/ZWave.' + cfg.dongle + '/Data/',
'/ZWave.' + cfg.dongle + '/Run/',
'/ZWave.' + cfg.dongle + '/Restore',
'/ZWave.' + cfg.dongle + '/InspectQueue',
 '/ZWave.' + cfg.dongle + '/FirmwareUpdate',
'/ZWave.' + cfg.dongle + '/ZMEBootloaderUpgrade',
'/ZWave.' + cfg.dongle + '/ZMEFirmwareUpgrade',
'/ZWave.' + cfg.dongle + '/ZMELicense',
'/ZWave.' + cfg.dongle + '/CreateZDDX/',
'/ZWave.' + cfg.dongle + '/CommunicationStatistics',
'/ZWave.' + cfg.dongle + '/PostfixGet',
'/ZWave.' + cfg.dongle + '/PostfixAdd',
'/ZWave.' + cfg.dongle + '/PostfixRemove',
'/ZWave.' + cfg.dongle + '/ExpertConfigGet',
'/ZWave.' + cfg.dongle + '/ExpertConfigUpdate'

**Comment by PoltoS** [comment]
All must be with. And Niels should remove the one w/o from the code.

**Comment by ronie-z-wave** [comment]
is there something w/o?  The UI is doing it - vades is currently adding all missing ZwaveAPI's to check for different instances

**Comment by vades** [comment]
Following APIS use dongle prefix:
'update_url': '/ZWave.' + dongle+ '/Data/',
            'store_url': '/ZWave.' + dongle+ '/Run/',
            'restore_url': '/ZWave.' + dongle+ '/Restore',
            'queue_url': '/ZWave.' + dongle+ '/InspectQueue',
            'fw_update_url': '/ZWave.' + dongle+ '/FirmwareUpdate',
            'zme_bootloader_upgrade': '/ZWave.' + dongle+ '/ZMEBootloaderUpgrade',
            'zme_firmware_upgrade': '/ZWave.' + dongle+ '/ZMEFirmwareUpgrade',
            'upload_bootloader': '/ZWave.' + dongle+ '/ZMEBootloaderUpgrade',
            'upload_firmware': '/ZWave.' + dongle+ '/ZMEFirmwareUpgrade',
            'license_load_url': '/ZWave.' + dongle+ '/ZMELicense',
            'stat_url': '/ZWave.' + dongle+ '/CommunicationStatistics',
            'postfixget_url': '/ZWave.' + dongle+ '/PostfixGet',
            'postfixadd_url': '/ZWave.' + dongle+ '/PostfixAdd',
            'postfixremove_url': '/ZWave.' + dongle+ '/PostfixRemove',
            'checklinks': '/ZWave.' + dongle+ '/CheckAllLinks',
            'zniffer_url': '/ZWave.' + dongle+ '/Zniffer',
            'communication_history_url': '/ZWave.' + dongle+ '/CommunicationHistory',
            'rssi_chart': '/ZWave.' + dongle+ '/RSSIGet',
            'configget_url': '/ZWave.' + dongle+ '/ExpertConfigGet',
            'configupdate_url': '/ZWave.' + dongle+ '/ExpertConfigUpdate',
            'call_all_nif': '/ZWave.' + dongle+ '/CallForAllNIF',
            'test_node': '/ZWave.' + dongle+ '/TestNode/',
            'network_statistics': '/ZWave.' + dongle+ '/Run/',
            'post_report_api': '/ZWave.' + dongle+ '/sendZWayReport',
            'reorg_run_url': '/ZWave.' + dongle+ '/NetworkReorganization',
            'reorg_log_url': '/ZWave.' + dongle+ '/GetReorganizationLog',
            'zddx_create_url': '/ZWave.' + dongle+ '/CreateZDDX/'

**Comment by PoltoS** [comment]
@ronie-z-wave all should be with as they are donlge specific.

**Comment by zwave-mke** [comment]
fixed
