### ISSUE TITLE
Restore backup with network topology not possible anymore

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#261]
Where is my favorite checkbox to restore the network? (v2.4.5 & 1.3.0)

**Comment by PoltoS** [comment]
hm.. found it.

Why can I restore netowrk topology only if I'm primary? I'm overriding my non=primary state with primary (based on my backup). Any idea behind it?

**Comment by vades** [comment]
Checkbox is hidden:
1. In the CIT
2.  If  controller is NOT isRealPrimary (Why? Have no idea :-)

**Comment by PoltoS** [comment]
2: We should at least make a notice like:
If you want to restore your secondary controller - do re-inclusion from your primary controller. If you want to restore another configuration - do a factory reset first.

This will help

**Comment by zwave-mke** [comment]
tested on 2.3.7 and is working
