### ISSUE TITLE
Can't upload image Route map more then 500.00 kb

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#264]
Why image should be so small? I propose to raise the limit to 20 mb.
<img width="1237" alt="2017-09-10 23 08 40" src="https://user-images.githubusercontent.com/2894860/30252569-84b80700-967d-11e7-9eaf-95390d757754.png">

**Comment by vades** [comment]
Why do you need 20 MB image? If you convert an image to (WEB)  JPG or PNG with image editor you get for this purpose (about 1000px x 1000px 72DPI ) image about 0.5 - 1MB MB. We can increase the limit to max 2MB.

**Comment by vades** [comment]
Another option is to upload the picture as SVG.

**Comment by aivs** [comment]
What is the image 0.5mb ? One black pixel?
Scheme of my apartment 4.6 mb in png, and 1.6 in jpg, 3000x2600 px.
1000x1000 it's a half of phone screen resolution - very small!

Need to biggest limit!

**Comment by aivs** [comment]
I see in dev in config.js size adjusted to 2048000 Bytes. I think 5mb would be perfect.
