### ISSUE TITLE
ExpertUI fails to load in Safari

### ISSUE THREAD

**Issue by ralphwetzel** [Z-Wave-Me/ExpertUI#266]
On Safari (seen at v11.0) the ExpertUI fails to load:

![expertui](https://user-images.githubusercontent.com/16342003/31056753-5d83cb00-a6d7-11e7-9936-d84bc7dfb57c.gif)

**Comment by aivs** [comment]
For me not a problem in Safari 11.
Open Expert UI directly with utl 192.168.178.48/expert.
Reset cache and reload page.

**Comment by ralphwetzel** [comment]
Thank you for your feedback.
Unfortunately this hasn't solved the issue. There seems to be a `404` error that constantly triggers a page reload.
I managed to capture the console. Perhaps this is of help to hunt the error.

![expertuierror1](https://user-images.githubusercontent.com/16342003/31133361-82fb5982-a85f-11e7-89d4-6ebe1e54d53f.png)

**Comment by vades** [comment]
1. Please can you provide your Expert Software and UI version. You find it in the  Network > Controller info
![controler-info](https://user-images.githubusercontent.com/1451741/31162503-2a69afba-a8de-11e7-86fd-3755fe7afe04.png)

2. Looks like missing a language file (en). Try to enter to your brouser: http://YOURIP:PORT/expert/app/lang/language.en.json Do you see an output?
![safari](https://user-images.githubusercontent.com/1451741/31162522-4d1d9864-a8de-11e7-84e2-2cf799992bd7.PNG)

**Comment by ralphwetzel** [comment]
I was experiencing this issue with Expert UI v2.3.5.
After upgrading to 2.3.6 everything works fine.
Thank you for your support!
R.
