### ISSUE TITLE
Add device version in Device Description list

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#267]
In Device Description list many items for same device with different versions. Need to add version in title, search will be easier.
<img width="1280" alt="2017-11-06 16 06 38" src="https://user-images.githubusercontent.com/2894860/32442728-7326f692-c30d-11e7-926b-7d088abdd4f1.png">

**Comment by vades** [comment]
The Device Description List is build from the /ZWave.zway/Run/devices[8].GuessXML() and there is now information about version.

![guessxml](https://user-images.githubusercontent.com/1451741/32482920-16b463e4-c39a-11e7-9d36-626004ccb9e6.png)
