### ISSUE TITLE
Not able to include Device

### ISSUE THREAD

**Issue by sunilphilip14** [Z-Wave-Me/ExpertUI#273]
I tried to include a device but it says '**_Unable to update data. controller.AddNodeToNetwork(1)_**'

![image](https://user-images.githubusercontent.com/37108265/37030870-9cf42bac-2190-11e8-9199-322fc7924efc.png)

**Comment by zwave-mke** [comment]
The error message: "Unable to update data. controller.AddNodeToNetwork(1)" is displayed if no valid license is activated on the UZB.

**Comment by spearway** [comment]
I have this problem also, I am running on Raspberry PI with OpenHab and Z-Way 2.3.x On the web site it says:
`If you use Z-Way on top of the RaZberry Shield the complete functionality is available free of charge without any limitations. You are allowed to change and adapt the UI and resell products based on the combination of RaZberry and Z-Way. No additional cost. Please check how to download Z-Way for Raspberry Pi.`
How do I get a valid license I am not opposed to pay for it but I cannot find any place to buy it.

**Comment by PoltoS** [comment]
If you are using a RaZberry, no need to buy anything - it should work out of the box.

If you use UZB, you need a license. Please write us on info@ or go to https://shop.zwave.eu/products/z-wave-controller/pc-adaptors-usb-dongles/541/z-wave.me-controller-software-z-way-license

**Comment by coronacoder** [comment]
What about the Demo Activation? If you enabled the Demo mode this should work for some period of time or not?

Just activated the demo mode and still experiencing the error message ..

**Comment by PoltoS** [comment]
Unlimited for two devices. Show your log. May be it was not activated
