### ISSUE TITLE
Can´t Install Z-Way on new RaspberryPi with Debian-stretch

### ISSUE THREAD

**Issue by RaGuKro** [Z-Wave-Me/ExpertUI#274]
Hello!

I startet an 1 week old good working RaspberryPi 3 with an fresh an unused Debain-stretch. Therefore I flashed the Debian Image from  https://www.raspberrypi.org/downloads/raspbian/

On the LXTerminal  I  typed:  wget -q -O - razberry.z-wave.me/install | sudo bash

The Installation reports some Errors because some Direchtories were not found. The Screenlines of the Installationprocedure you will see at the End.

When I type on an other PC in the same Network http://find.z-wave.me, I will NOT see the Raspberry-IP below. When I type the RaspberryPi-IP:8083 the Webpage I will get  "SmartHome UI - ERROR
Unable to load data"

Restarting the Pi has no effect.
The Razberry hardware seems to be OK: On a second Try I installed the Razberry Image (http://razberry.z-wave.me/z-way-server/razberry.img.zip) and everything is OK.
But I want the Debian-stretch with the GUI and VNC.

What can I do to solve the problem - thx

Installation Screenlines:
`pi@raspberrypi:~ $ wget -q -O - razberry.z-wave.me/install | sudo bash
Do you accept Z-Wave.Me licence agreement?
Please read it on Z-Wave.Me web site: http://razberry.z-wave.me/docs/ZWAYEULA.pdf
yes/no: YES
Please answer yes or no
yes/no: yes
z-way-server new installation
Installing additional libraries
Hit:1 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Fetched 25.3 kB in 1s (23.6 kB/s)                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tzdata is already the newest version (2018c-0+deb9u1).
Suggested packages:
  gawk-doc sharutils-doc bsd-mailx | mailx
The following NEW packages will be installed:
  gawk libc-ares2 libsigsegv2 sharutils
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 848 kB of archives.
After this operation, 3,598 kB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libsigsegv2 armhf 2.10-5 [28.4 kB]
Get:2 http://mirrordirector.raspbian.org/raspbian stretch/main armhf gawk armhf 1:4.1.4+dfsg-1 [508 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian stretch/main armhf sharutils armhf 1:4.15.2-2 [236 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libc-ares2 armhf 1.12.0-1+deb9u1 [76.0 kB]
Fetched 848 kB in 0s (1,026 kB/s)    
Selecting previously unselected package libsigsegv2:armhf.
(Reading database ... 124889 files and directories currently installed.)
Preparing to unpack .../libsigsegv2_2.10-5_armhf.deb ...
Unpacking libsigsegv2:armhf (2.10-5) ...
Setting up libsigsegv2:armhf (2.10-5) ...
Selecting previously unselected package gawk.
(Reading database ... 124899 files and directories currently installed.)
Preparing to unpack .../gawk_1%3a4.1.4+dfsg-1_armhf.deb ...
Unpacking gawk (1:4.1.4+dfsg-1) ...
Selecting previously unselected package sharutils.
Preparing to unpack .../sharutils_1%3a4.15.2-2_armhf.deb ...
Unpacking sharutils (1:4.15.2-2) ...
Selecting previously unselected package libc-ares2:armhf.
Preparing to unpack .../libc-ares2_1.12.0-1+deb9u1_armhf.deb ...
Unpacking libc-ares2:armhf (1.12.0-1+deb9u1) ...
Processing triggers for install-info (6.3.0.dfsg.1-1+b1) ...
Setting up sharutils (1:4.15.2-2) ...
Setting up gawk (1:4.1.4+dfsg-1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libc-ares2:armhf (1.12.0-1+deb9u1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Installing additional libraries for HomeKit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libavahi-client-dev libavahi-common-dev libavahi-compat-libdnssd1
  libdbus-1-dev
The following NEW packages will be installed:
  libavahi-client-dev libavahi-common-dev libavahi-compat-libdnssd-dev
  libavahi-compat-libdnssd1 libdbus-1-dev
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 423 kB of archives.
After this operation, 1,277 kB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libavahi-common-dev armhf 0.6.32-2 [62.6 kB]
Get:2 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libdbus-1-dev armhf 1.10.26-0+deb9u1 [201 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libavahi-client-dev armhf 0.6.32-2 [56.5 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libavahi-compat-libdnssd1 armhf 0.6.32-2 [44.0 kB]
Get:5 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libavahi-compat-libdnssd-dev armhf 0.6.32-2 [58.8 kB]
Fetched 423 kB in 0s (474 kB/s)                    
Selecting previously unselected package libavahi-common-dev:armhf.
(Reading database ... 125114 files and directories currently installed.)
Preparing to unpack .../libavahi-common-dev_0.6.32-2_armhf.deb ...
Unpacking libavahi-common-dev:armhf (0.6.32-2) ...
Selecting previously unselected package libdbus-1-dev:armhf.
Preparing to unpack .../libdbus-1-dev_1.10.26-0+deb9u1_armhf.deb ...
Unpacking libdbus-1-dev:armhf (1.10.26-0+deb9u1) ...
Selecting previously unselected package libavahi-client-dev:armhf.
Preparing to unpack .../libavahi-client-dev_0.6.32-2_armhf.deb ...
Unpacking libavahi-client-dev:armhf (0.6.32-2) ...
Selecting previously unselected package libavahi-compat-libdnssd1:armhf.
Preparing to unpack .../libavahi-compat-libdnssd1_0.6.32-2_armhf.deb ...
Unpacking libavahi-compat-libdnssd1:armhf (0.6.32-2) ...
Selecting previously unselected package libavahi-compat-libdnssd-dev:armhf.
Preparing to unpack .../libavahi-compat-libdnssd-dev_0.6.32-2_armhf.deb ...
Unpacking libavahi-compat-libdnssd-dev:armhf (0.6.32-2) ...
Setting up libdbus-1-dev:armhf (1.10.26-0+deb9u1) ...
Setting up libavahi-common-dev:armhf (0.6.32-2) ...
Setting up libavahi-client-dev:armhf (0.6.32-2) ...
Setting up libavahi-compat-libdnssd1:armhf (0.6.32-2) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Setting up libavahi-compat-libdnssd-dev:armhf (0.6.32-2) ...
Making symlinks to libssl.so
Making symlinks to libcrypto.so
Installing libarchive-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  libarchive-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 427 kB of archives.
After this operation, 1,227 kB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libarchive-dev armhf 3.2.2-2 [427 kB]
Fetched 427 kB in 0s (1,136 kB/s)
Selecting previously unselected package libarchive-dev:armhf.
(Reading database ... 125205 files and directories currently installed.)
Preparing to unpack .../libarchive-dev_3.2.2-2_armhf.deb ...
Unpacking libarchive-dev:armhf (3.2.2-2) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libarchive-dev:armhf (3.2.2-2) ...
Making link to libarchive.so.12
Getting Z-Way for Raspberry Pi and installing
--2018-03-14 15:03:39--  http://razberry.z-wave.me/z-way-server/z-way-server-RaspberryPiXTools-v2.3.6.tgz
Resolving razberry.z-wave.me (razberry.z-wave.me)... 185.25.224.239
Connecting to razberry.z-wave.me (razberry.z-wave.me)|185.25.224.239|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://oldrazberry.z-wave.me/z-way-server/z-way-server-RaspberryPiXTools-v2.3.6.tgz [following]
--2018-03-14 15:03:39--  https://oldrazberry.z-wave.me/z-way-server/z-way-server-RaspberryPiXTools-v2.3.6.tgz
Resolving oldrazberry.z-wave.me (oldrazberry.z-wave.me)... 46.20.244.36
Connecting to oldrazberry.z-wave.me (oldrazberry.z-wave.me)|46.20.244.36|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19893339 (19M) [application/x-gzip]
Saving to: ‘/tmp/z-way-server-RaspberryPiXTools-v2.3.6.tgz’

z-way-server-Raspbe 100%[===================>]  18.97M   877KB/s    in 15s     

2018-03-14 15:03:54 (1.28 MB/s) - ‘/tmp/z-way-server-RaspberryPiXTools-v2.3.6.tgz’ saved [19893339/19893339]

Extracting new z-way-server
New version z-way-server installed
Creating Z-Way startup script
Adding z-way-server to autostart
Getting Webif for Raspberry Pi and installing
--2018-03-14 15:04:00--  http://razberry.z-wave.me/webif_raspberry.tar.gz
Resolving razberry.z-wave.me (razberry.z-wave.me)... 185.25.224.239
Connecting to razberry.z-wave.me (razberry.z-wave.me)|185.25.224.239|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://oldrazberry.z-wave.me/webif_raspberry.tar.gz [following]
--2018-03-14 15:04:01--  https://oldrazberry.z-wave.me/webif_raspberry.tar.gz
Resolving oldrazberry.z-wave.me (oldrazberry.z-wave.me)... 46.20.244.36
Connecting to oldrazberry.z-wave.me (oldrazberry.z-wave.me)|46.20.244.36|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 412185 (403K) [application/x-gzip]
Saving to: ‘STDOUT’

-                   100%[===================>] 402.52K  1019KB/s    in 0.4s    

2018-03-14 15:04:01 (1019 KB/s) - written to stdout [412185/412185]

First install, getting Remote ID
--2018-03-14 15:04:01--  http://find.zwave.me/zbw_new_user
Resolving find.zwave.me (find.zwave.me)... 46.20.244.72, 78.46.43.211
Connecting to find.zwave.me (find.zwave.me)|46.20.244.72|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/zbw_connect_setup.run’

/tmp/zbw_connect_se     [ <=>                ]   6.10K  --.-KB/s    in 0s      

2018-03-14 15:04:02 (125 MB/s) - ‘/tmp/zbw_connect_setup.run’ saved [6244]

Do you want to enable the remote support(y/n)? Remote support NOT enabled
Now you can run zbw_connect with /etc/init.d/zbw_connect start
or simply reboot your system

Your user id: 108583
Your password: <deleted Password>
[ ok ] Starting zbw_connect (via systemctl): zbw_connect.service.
/tmp/zbw_autosetup: line 15: insserv: command not found
Getting webserver mongoose for Webif
--2018-03-14 15:04:13--  http://razberry.z-wave.me/mongoose.pkg.rPi.tgz
Resolving razberry.z-wave.me (razberry.z-wave.me)... 185.25.224.239
Connecting to razberry.z-wave.me (razberry.z-wave.me)|185.25.224.239|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://oldrazberry.z-wave.me/mongoose.pkg.rPi.tgz [following]
--2018-03-14 15:04:14--  https://oldrazberry.z-wave.me/mongoose.pkg.rPi.tgz
Resolving oldrazberry.z-wave.me (oldrazberry.z-wave.me)... 46.20.244.36
Connecting to oldrazberry.z-wave.me (oldrazberry.z-wave.me)|46.20.244.36|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44749 (44K) [application/x-gzip]
Saving to: ‘/tmp/mongoose.pkg.rPi.tgz’

mongoose.pkg.rPi.tg 100%[===================>]  43.70K  --.-KB/s    in 0.1s    

2018-03-14 15:04:14 (321 KB/s) - ‘/tmp/mongoose.pkg.rPi.tgz’ saved [44749/44749]

Adding mongoose to autostart
Start mongoose http server
[ ok ] Starting mongoose (via systemctl): mongoose.service.
Raspberry Pi 3 Detected. Disabling Bluetooth
Removed /etc/systemd/system/multi-user.target.wants/hciuart.service.
Adding 'dtoverlay=pi3-miniuart-bt' to /boot/config.txt
!!! Update Raspberry Pi 3 Firmware for stability work with commands:
sudo apt-get install rpi-update
sudo rpi-update
ls: cannot access 'config/zddx/*.xml': No such file or directory
Usage: ./z-cfg-update <filename>
diff: /etc/inittab: No such file or directory
diff: /tmp/zway_install_inittab: No such file or directory
Preparing AMA0 interface:
 removing 'console=ttyAMA0,115200' and 'kgdboc=ttyAMA0,115200 and 'console=serial0,115200' from kernel command line (/boot/cmdline.txt)
 removing '*:*:respawn:/sbin/getty ttyAMA0' from /etc/inittab
mv: cannot stat '/tmp/zway_install_inittab': No such file or directory
AMA0 interface reconfigured, please restart Raspberry
Do you want to receive emails with news about RaZberry project?
! Please subscribe again if you did it before 30.03.2013
yes/no: no
Thank you for using RaZberry!
pi@raspberrypi:~ $ 
`

**Comment by 5oP** [comment]
Look at this:
http://www.zwave.de/groups/razberry-user/forum/topic/z-way-unter-raspian-strech/

**Comment by zwave-mke** [comment]
please use: **wget -q -O - support.zwave.eu/libs | sudo bash** to update your libs
