### ISSUE TITLE
secure inclusion error: secure channel not established by primary controller - skipping security

### ISSUE THREAD

**Issue by nostroff** [Z-Wave-Me/ExpertUI#279]
Hello. I installed version 2.3.8-rc8 on a Raspberry Pi running stretch. I'm encountering a problem when trying to securely include a Schlage Connect deadbolt. A log entry that shows the following:

[2018-09-30 15:47:30.819] [W] [zway] Node 28:0 CC Security: secure channel not established by primary controller - skipping security

This log entry is unexpected as the RaZberry daughter board is the only controller in the network.

Perhaps related, the Network->Control->Device Management panel shows "Force unsecure inclusion" even though I select the "secure" button.

More of the z-way server log is attached.

[z-way-server.log](https://github.com/Z-Wave-Me/ExpertUI/files/2432151/z-way-server.log)

Please let me know if you would like more information or access.

Thanks.

**Comment by nostroff** [comment]
This bug report can be closed - doing a factory reset on the controller fixed the problem (which requires rebuilding the Z-Wave network).

**Comment by PoltoS** [comment]
I think this is related to a wrong isRealPrimary value reported by the RaZberry during the first boot. Factory reset heals this. It would be nice to see the problem before you have resetted it. But it is too late ;(
