### ISSUE TITLE
Update year at the footer

### ISSUE THREAD

**Issue by fenst** [Z-Wave-Me/ExpertUI#282]
Hi. 
UI version 1.5.0 still have "_© 2018 by Z-Wave.Me_" at the footer. Could you update the year to "2019", please?

![2019-07-29 22_24_42-Параметры](https://user-images.githubusercontent.com/5321637/62076218-c80d8300-b24f-11e9-9f26-d60e779257ce.png)

**Comment by PoltoS** [comment]
https://github.com/Z-Wave-Me/ExpertUI/commit/c08d0ba7ba220745eb5e1b05593e0c33e9b38913
