### ISSUE TITLE
Indicator command class 

### ISSUE THREAD

**Issue by nostroff** [Z-Wave-Me/ExpertUI#287]
I see the expert UI in Z-Way 3.2.2 supports newer versions of the Indicator command class (higher than Indicator command class version 1). However, it looks like libzway is only capable of sending version 1 Indicator messages. Am I doing something wrong? If not, can you please reply with info on when libzway will support newer versions of the Indicator command class?

Thanks,
Neil

**Comment by PoltoS** [comment]
We are preparing a very new Z-Way supportiy the latest Indicator as well as many other features mandatory in Z-Wave Plus v2. We plan to finalize tests in February and release a beta for public. It should be called v4.0.0.


This is why Expert UI was adopted, but the libzway in v3.2.2 is not yet.

**Comment by PoltoS** [comment]
Should work now in v4.0.2

**Comment by nostroff** [comment]
Thanks!
