### ISSUE TITLE
On Type info tab before App version show Manufacturer and Product Name

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#38]
Otherwise App version is usefull

**Comment by vades** [comment]
1.Where can I get  the manufacturer? node.data.vendorString.value ???
2. Where can I get  the Product Name?

**Comment by PoltoS** [comment]
Product name only from ZDDX, manufacturer is node.data.vendorString.value.

May be two columns is a good idea - manufacturer will be show always (even if no ZDDX selected) and if present, in another column show Product Name from ZDDX. Then will be App version

**Comment by vades** [comment]
Columns Vendor and Product are shown:
1. Vendor from node.data.vendorString.value.
2. Product from ZDDXml
