### ISSUE TITLE
Add label with real frequency

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#42]
It is convenient to know what frequency is currently working a controller. When the frequency changes, we will see that has changed is the frequency.

**Comment by aivs** [comment]
After frequency change showed previous frequency, not actual

**Comment by vades** [comment]
It has long been finished
![frequency](https://cloud.githubusercontent.com/assets/1451741/16260529/1f855a82-3868-11e6-9f76-a6b814dc88f7.png)

**Comment by aivs** [comment]
The issue isn't resolved, but it's a backend issue.

**Comment by vades** [comment]
OK :-)
