### ISSUE TITLE
Allow to work with multiple Z-Wave dongles

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#43]
Please make a selector in Expert UI on the top that will allow to change Z-Way API to work with.

/ZWave/list gives you a list of available Z-Way objects. Some button nearby should allow to refresh it (or just refresh of UI is ok). Once one is selected (on load select first one), change all API URLs and reload all the objects from server. This is pretty same as selecting IP server to connect.

Old /ZWaveAPI/... should be changed to /ZWave/<name>/... So there should be no /ZWaveAPI anymore (this becomes legacy now).

**Comment by vades** [comment]
New Issue https://github.com/Z-Wave-Me/ExpertUI/issues/153
