### ISSUE TITLE
Thermostat view does not work for Stella Z

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#45]
The thermostat control is not shown in Thermostat view (example is device 9):
http://forum.z-wave.me/download/file.php?id=199

**Comment by vades** [comment]
The control is shown if:
1. var hasThermostatSetpoint = 0x43 in instance.commandClasses;
2. instance.commandClasses[0x43].data[curThermMode]

What to display when the device does not meet these conditions?
In the Old Blue UI is shown button "Change mode" - whitch does not works.

**Comment by PoltoS** [comment]
Can we discuss in Skype what does not work in Old Blue UI?

Do you have a Stella Z with you?

**Comment by vades** [comment]
Fixed
