### ISSUE TITLE
Show Instance0 for Multichannel devices

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#48]
The interface displays only the Instance1 and Instance2, Instance0 is not displayed, it is also necessary to show.
![instance0](https://cloud.githubusercontent.com/assets/2894860/5454116/cb8b5036-853e-11e4-9fe4-3401c905c5c6.png)
Should be as shown

**Comment by vades** [comment]
Are you sure? In Old Blue UI are instances displayed in the section "Switches" only
