### ISSUE TITLE
Make the interface more compact

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#49]
The distance between elements is very large.
Have to scroll down, but if you make the interface more compact, essential elements will fit on the screen.  
**Original**
![original](https://cloud.githubusercontent.com/assets/2894860/5503995/e34ed498-878e-11e4-829a-b8430ea34d07.png)

**Compact**
![small](https://cloud.githubusercontent.com/assets/2894860/5504008/fabdc198-878e-11e4-89d1-1d08c98f4d18.png)

**Comment by vades** [comment]
All tables now have less space
