### ISSUE TITLE
Add bitrange support and add description in the Configuration

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#50]
In the Configuration there is no description, and no support bitrange. In Old Expert all OK
![newexpert-oldexpert](https://cloud.githubusercontent.com/assets/2894860/5537559/bcb67ce0-8ab4-11e4-8bd8-80652b61b47c.png)

**Comment by PoltoS** [comment]
and bitset too.

**Comment by vades** [comment]
What device on http://zwave.dyndns.org:8083/expert/ has a bitset config type?

**Comment by PoltoS** [comment]
Select for some device having Configuration CC ZDDX from Remotec ZXT-120 (this one: http://www.pepper1.net/zwavedb/device/617)

**Comment by vades** [comment]
I have included ZXT-120 and has no configuration:
http://zwave.dyndns.org:8083/expert/#/config/configuration/100

**Comment by PoltoS** [comment]
Of course you need to select this ZDDX on a device that have Configuration CC. Otherwise no UI will be rendered for Configuration despite ZDDX

**Comment by vades** [comment]
ZXT-120 is installed with configuration but BITSET has now data even in the old version
http://zwave.dyndns.org:8083/expert/#/config/configuration/100

1. What device can displays BITSET data and what to do to display BITSET?
2. What  BITSET have to display? bitcheck: ???  bitrange: ??

**Comment by PoltoS** [comment]
Make sure P1 record is correct

**Comment by aivs** [comment]
ZXT-120 record on pepper1 correct http://pepper1.net/zwavedb/device/617

**Comment by PoltoS** [comment]
@vades We should finish this task after more than a year

**Comment by vades** [comment]
I've intagrated bitrange support and tested with device description from Aeotec Mulitsensor 6-in1
Displaing the inputs works but I thing that wrong commands are send.
The problem is I want to compare comands with commands from the Old Blue UI from https://github.com/Z-Wave-Me/BlueExpertUI
and this UI does not works anymore with Firmware version	v2.2.2
Download a version from https://github.com/Z-Wave-Me/ExpertUI/tree/ref-bitrange and let me know what is wrong.

**Comment by aivs** [comment]
1) Now sends many command, should send one command with sum of all bits, as example, I set 1 and 4, so need to send 5=1+4 
1 +  
2  
4 +  
8  
16  
32  

2) Not showing what bits are set. If value 15, so bits 1,2,4,8 are set. See calculator.
<img width="1280" alt="2016-06-15 17 00 50" src="https://cloud.githubusercontent.com/assets/2894860/16082692/091fd184-331b-11e6-8beb-8f344dcd6b8a.png">

**Comment by aivs** [comment]
Send wrong command, many arguments!
<img width="1280" alt="2017-03-09 19 04 03" src="https://cloud.githubusercontent.com/assets/2894860/23758564/402f1d26-04fb-11e7-8652-2cae34c66dd5.png">

**Comment by vades** [comment]
How should this looks like?
- How many arguments should be there?
- Please provide example of the request with correct  arguments

**Comment by aivs** [comment]
bit0 - 1
bit1 - 2
bit2 - 4
bit3 - 8
bit4 - 16
bit5 - 32
bit6 - 64
bit6 - 128

For example, parameter 101. I set:
Bit0(Battery) - 1 
Bit1(Not used)
Bit2(Not used)
Bit3(Not used)
Bit4(Ultraviolet) - 16 
Bit5(Temperature) - 32
Bit6(Humidity) - 64
Bit7(Luminance) - 128

Need to sum all set bits, 1 + 16 + 32+ 64 + 128 = 241.
Command should be: 
**/ZWave.zway/Run/devices[10].instances[0].commandClasses[0x70].Set(101,241,4)**

**Comment by vades** [comment]
Thanks. I'll add it into our internal  Task Manager
