### ISSUE TITLE
Add button "Save this parameter into Device", to each configuration parameters

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#51]
When pressing the button "Save into Device" send values for all parameters. Some devices are configured using parameters, for example ZXT-120. For this device need to send the parameter values separately.
![configintodevice](https://cloud.githubusercontent.com/assets/2894860/5538139/27eb2b6e-8abf-11e4-875d-f8a8628f3109.png)

**Comment by vades** [comment]
Done

**Comment by PoltoS** [comment]
Seems it has gone after last update. Possible to get back?

**Comment by vades** [comment]
CP told me: remove this button.

**Comment by vades** [comment]
Button is back
