### ISSUE TITLE
ZDDX contains null instead of all fields

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#52]
Here is the problematic ZDDX:
http://zwave.dyndns.org:8083/expert/#/config/configuration/15 (Configuration tab)

**Comment by vades** [comment]
All updates are on:
1. http://zwave.dyndns.org:8083/expert/
2. GIT

**Comment by PoltoS** [comment]
Could you make it available online, please?

**Comment by PoltoS** [comment]
Still a problem
