### ISSUE TITLE
Add progress to firmware update tab

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#53]
In Configuration->FirmwareUpgrade add a lider (or just a caption) with % of progress.

% = FirmwareUpdate.data.fragmentTransmitted.value / FirmwareUpdate.data.fragmentCount.value \* 100

**Comment by vades** [comment]
FirmwareUpdate.data.fragmentTransmitted.value / FirmwareUpdate.data.fragmentCount.value
1. This is a Zwavapi data holder node?
2. Where and What is error response - if something is wrong with firmware update?
3. Where and What is the response if firmware update is dan

**Comment by PoltoS** [comment]
1. yes
2. and 3. there is no error message. but indeed we can show last status: FirmwareUpdate.data.updateStatus
#define FIRMWARE_UPDATE_MD_STATUS_REPORT_UNABLE_TO_RECEIVE_WITHOUT_CHECKSUM_ERROR        0x00
#define FIRMWARE_UPDATE_MD_STATUS_REPORT_UNABLE_TO_RECEIVE                               0x01
#define FIRMWARE_UPDATE_MD_STATUS_REPORT_SUCCESSFULLY_MANUAL_RESTART                     0xFE
#define FIRMWARE_UPDATE_MD_STATUS_REPORT_SUCCESSFULLY                                    0xFF

**Comment by PoltoS** [comment]
Why closed?

**Comment by vades** [comment]
FirmwareUpdate.data.updateStatus,values returns NULL only and it doesn't matter what happens during upgrade process

**Comment by PoltoS** [comment]
Please show me the log of upgrade. Few tens of first lines are enough

**Comment by ronie-z-wave** [comment]
Should be done with latest commits on develop branch :)

**Comment by PoltoS** [comment]
Does it work? Do you changes in fragmentTransmitted?

**Comment by ronie-z-wave** [comment]
I do fragmentsCount/fragmentsTransmitted ... has worked in my tests - should be in the new build now

btw. any idea to this? https://github.com/Z-Wave-Me/ExpertUI/issues/242

**Comment by ronie-z-wave** [comment]
Done.
