### ISSUE TITLE
Commands are listed twice in Expert commands

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#57]
Example is device  15

**Comment by vades** [comment]
I can not see this

**Comment by PoltoS** [comment]
Proof:
https://www.uploady.com/#!/download/OU4J2Hxnsxl/kCD8l1ItpXA2jgYG

**Comment by vades** [comment]
The problem occurs when:
1. Clicked on Expert commands tab
2. Then clicked on Interview tab
3.  Clicked back on Experd commands tab

Fixed
