### ISSUE TITLE
Seems that on Update button press sensors on all channels of a device show same value

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#60]
Take a device with several channels and SensorMultilevel inside. Press update button and you will see them all show same value.

Blue UI still shows correct values

**Comment by PoltoS** [comment]
http://forum.z-wave.me/viewtopic.php?f=3419&t=21055#p54228

**Comment by vades** [comment]
I fixed rowID and should works:
I have same results in old blue UI as in new UI (old UI does not displays alarmSensor)
![sensors_old](https://cloud.githubusercontent.com/assets/1451741/5901961/cfa5f6d2-a576-11e4-8d6d-48b6c76e98b2.png)
![sensors_new](https://cloud.githubusercontent.com/assets/1451741/5901962/d11ee58c-a576-11e4-8b45-9e230d232ad7.png)
