### ISSUE TITLE
Show values that are to be saved in the device and actual values.

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#63]
The current UI lacks of big part that Blue UI had:
Then new values are applied, we need to still show current (until device reports back changed values) and show that is to be set.

We told about this many times: show in controls the value to be saved and somehow else what is currently.

In Blue UI for fix we use underscore to show current selection, for range/string we use after the field "(value)". For node we show selection as red in the list. Of course if there is an enum, we show that only for current enum item.

For associations we used colors. May be do same or propose better way to show current state and desired state.

This applies to Config, Associations, Wakeup, Protection.

In Blue UI old values were taken from Configuration.xml. UYou can use some JSON in new Expert UI to store it or use session local storage only (also acceptable - will be lost on UI close, but should survive refresh).

**Comment by vades** [comment]
Now are config data saved into Configuration.xml
Please test it.
