### ISSUE TITLE
In Association Remove

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#67]
Check device 15

Group 1:
remove all
try to add 1.1. Only 1 can be added. add 1
try to add 1.1 again: 1 is not in the list anymore. should be

If you manage to add 1.1, 1.2, 1.3 and 1, you will see another problem on delete:
if channel is selected "<select....>" - 1 is deleted - not obvious - should be "no channel" string
if channel is selected "" - some (may be first) is deleted - not obvious neither - should not be in the list
if channel is 1,2,3 - correct behavior

And I want to remind that if only one in group is left, on remove pre-select it (device and channel - in fact if list item is the only one, preselect it).

**Comment by vades** [comment]
On my site adding and deleting device to/from group does not works:

Example Device_15 on Group 1 is assigned to the first button. :
Deleting assoc 1.1: http://zwave.dyndns.org:8083/ZWaveAPI/Run/devices[15].instances[0].commandClasses[0x8e].Remove(1,1,1)
No assoc deleted

Deleting assoc 1.2: http://zwave.dyndns.org:8083/ZWaveAPI/Run/devices[15].instances[0].commandClasses[0x8e].Remove(1,1,2)
No assoc deleted

Deleting assoc 1.3: http://zwave.dyndns.org:8083/ZWaveAPI/Run/devices[15].instances[0].commandClasses[0x8e].Remove(1,1,3)
No assoc deleted

Adding assoc: 
http://zwave.dyndns.org:8083/ZWaveAPI/Run/devices[15].instances[0].commandClasses[0x85].Set(1,100)
No assoc added

Is there something wrong with request?

**Comment by PoltoS** [comment]
Sure! Device is offline! It is marked as Dead. Please turn it on or use another similar for reference

**Comment by vades** [comment]
Device_5 is not dead and can't delete association:
http://zwave.dyndns.org:8083/expert/#/config/configuration/5

http://zwave.dyndns.org:8083/ZWaveAPI/Run/devices[5].instances[0].commandClasses[0x8e].Remove(1,134)
TypeError: Cannot read property 'Remove' of undefined

What is wrong?

**Comment by PoltoS** [comment]
Martin, of course!! device 5 do not have MultiChannelAssociations!!!

**Comment by PoltoS** [comment]
So, have you reproduced it?

**Comment by vades** [comment]
See my email: ExpertUI - configuration and associations from 09. 02. 2015 with my questions.
Associations are done by my  colleague and he does not work here anymore.
Can you please to explain in more detail how associations work?

**Comment by vades** [comment]
Associations code refactored
