### ISSUE TITLE
Add "Wakeup time, seconds" string into lang file for translating

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#68]
At the tab Configuration-->Device-->Configuration at the bottom of the page there is a string
 "Wakeup time, seconds" not in the lang file. I Cannot add a translation.
![2015-01-23 16 27 16](https://cloud.githubusercontent.com/assets/2894860/5875351/2b0bd426-a31d-11e4-9335-a4e29b00d16d.png)

**Comment by vades** [comment]
This text comes from the backend.

**Comment by PoltoS** [comment]
Nit possible!
What is the stakeholder name where it comes from?

**Comment by PoltoS** [comment]
I meant dataholder

**Comment by vades** [comment]
Name comes from: pyzw_zwave_ui.js and there is now translations:
case 0x84:
			return {
				"Get": [],
				"CapabilitiesGet": [],
				"Set": [
				       {
						"label": "Wakeup time, seconds",
						"type": {
