### ISSUE TITLE
Suggestion: Device Certification Number in Configuration Interview screen

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#69]
It would be good to have the Certification Number of a device somewhere in the Interview menu. I did notice that these numbers are available for many devices in the Pepper1 database. I don't know if that database is rugged enough to return the correct number on the basis of device interview results.

As a side note, it might also be usefull to see at a glance if de vice is zwave plus or not.

**Comment by PoltoS** [comment]
Z-Wave Plus is already shown on Type Info page.

Not sure if cert if worth to show, since user will anyway not make use of it (other that he knows it was certified).

**Comment by pz1** [comment]
This knowledge would empower users. Close adherence to these standards is also beneficial for Z-Way because of the way you implemented z-wave.
I do understand there are other more pressing issues to be fixed. So if you want to close the issue, that is fine with me.
