### ISSUE TITLE
RaZberry device named Device_1 on association tab, Routing Table. Shoud be "RaZberry"

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#70]
![2015-01-26 15 43 48](https://cloud.githubusercontent.com/assets/2894860/5899815/3525eff8-a572-11e4-94e7-0d1531c20248.png)  
![2015-01-26 15 46 40](https://cloud.githubusercontent.com/assets/2894860/5899844/8aadbbf4-a572-11e4-808d-25aa51bee18e.png)  
On Configuration tab OK 
![2015-01-26 15 47 05](https://cloud.githubusercontent.com/assets/2894860/5899858/c1997112-a572-11e4-86a1-3cc0fcc749c0.png)

**Comment by vades** [comment]
Done
