### ISSUE TITLE
Restore backup does not have <input file> field.

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/ExpertUI#71]
It is not present anymore. Why?

Please do it asap too.

**Comment by vades** [comment]
Is shown when click on: Are your sure ot overwrite the network configuration....
![network_restore](https://cloud.githubusercontent.com/assets/1451741/5914985/5ee775a4-a5ff-11e4-9573-ae24904995ef.png)

**Comment by PoltoS** [comment]
Why closed?

Where is the input type=file??? How to select file?

**Comment by vades** [comment]
Restore backup has now intuitive field name "Pick up the file"
![network_restore](https://cloud.githubusercontent.com/assets/1451741/5937480/4db399ec-a6f0-11e4-98a7-7a5654acf90c.png)

**Comment by Mirarkitty** [comment]
Clicking on the field does nothing in Firefox. Works fine in Chrome though. 
No javascript console output or errors.
