### ISSUE TITLE
Express Control Ezmotion has one value for Motion, Luminiscence, Temperature 

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#72]
Device: Express Control EZMotion 2.1 (2011 year)
If you update the temperature, then Motion, Luminiscence, Temperature will have the value of the Temperature.
If you update the luminiscence, then Motion, Luminiscence, Temperature will have the value of the Luminiscence.

![2015-01-27 10 43 42](https://cloud.githubusercontent.com/assets/2894860/5915070/aadd03e0-a611-11e4-9898-672b074337d6.png)

In Old Blue UI all OK
![2015-01-27 10 43 55](https://cloud.githubusercontent.com/assets/2894860/5915095/fe264a2a-a611-11e4-8865-e4720441b7ac.png)

**Comment by vades** [comment]
See: https://github.com/Z-Wave-Me/ExpertUI/issues/60
