### ISSUE TITLE
Incorrect table rows id's in expert/#/control/sensors

### ISSUE THREAD

**Issue by lttn** [Z-Wave-Me/ExpertUI#76]
If one device has many sensors of one type (which has different instance id), on update one value of this, updated all sections of this device with the same value. I think, this is bug of UI, because some of table row has repeated id's.

**Comment by PoltoS** [comment]
Похоже на направленную задачу #60. Пробовали в rc12?

**Comment by lttn** [comment]
да, в отличие от 2.0.0 в 2.0.1RC12, помимо неправильно генерящихся идентификаторов строк, еще и апдейт по кнопке не работает. В 2.0 можно было посмотреть правильное значение с любого датчика, нажав кнопку "обновить" напротив него. При этом требуемый параметр считывался и отображался во все инстансы девайса. Причем неправильно работает только обновление - при первоначальной загрузке страницы идентификаторы генерятся правильно.

**Comment by vades** [comment]
FIXED cca 1 month ago

**Comment by lttn** [comment]
Unfortunetely not confirmed: there is this bug in rc14.
![3333](https://cloud.githubusercontent.com/assets/9655273/6392507/59d1ade2-bdd2-11e4-93fa-3b661ba98c72.png)
