### ISSUE TITLE
Show the set temperature for Thermostat

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#77]
In Thermostat  widget I can't see what the temperature I set, need to show the value of the slider. For the dimmer it is also necessary. Temperature field show temperature that I set in blueUI, but I can't change this temperature in ExpertUI.
![2015-02-06 17 10 57](https://cloud.githubusercontent.com/assets/2894860/6080793/5917b3f4-ae25-11e4-97a2-4dd1c0470b3c.png)

**Comment by vades** [comment]
Done
