### ISSUE TITLE
не работает удаление ассоциации

### ISSUE THREAD

**Issue by chorus12** [Z-Wave-Me/ExpertUI#78]
В новом экспертном интерфейсе не работает удаление ассоциации у устройств. Проблемы две:
1) На уровне интерфейса - указываешь удалить одно устройство из ассоциации, а удаляется другое
2) На уровне сети z-wave - ассоциация не удаляется 
Уточнение - пытаюсь удалить ассоциацию с удалённым из сети устройством. 
Версия 2.0.1 rc-11

**Comment by PoltoS** [comment]
Reworked
