### ISSUE TITLE
Configuration does not show bitfields properly

### ISSUE THREAD

**Issue by Mirarkitty** [Z-Wave-Me/ExpertUI#79]
Bitfield properties like Aeon Labs Multisensor parameter 101 or Philio PST02-A parameter 5 only show up as "bitset" (not even parameter number).
![bitset](https://cloud.githubusercontent.com/assets/3462581/6234820/fc43b2b0-b6dd-11e4-91fc-8847a944ae7b.png)

**Comment by vades** [comment]
See: https://github.com/Z-Wave-Me/ExpertUI/issues/50
