### ISSUE TITLE
Wake-up parameter 'always' null

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/ExpertUI#81]
Using v2.0.1-rc12
Wake-up parameter always null. 
Something broken in services.js->configWakeupCont().
758: var cfgFile = getCfgXmlParam(cfgXml, nodeId, '0', '84', 'Set'); - anyway return []
so it can not be 
774: if (cfgFile !== undefined)

Addition - That was newly included device, if I chnage parameter manually the value is not null then, but in device the value is not updated.(does not goes in job queue and not in log)

![wakeupalwaysnull](https://cloud.githubusercontent.com/assets/5053583/6352803/b50769b0-bc5e-11e4-8f2a-8fa56b6dac07.png)

**Comment by vades** [comment]
Fixed
