### ISSUE TITLE
Wrong status for Alarm sensor

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/ExpertUI#82]
2.0.1-rc15 (ex. for Fibaro FGMS Alarm sensor class)

There is a wrong status for 'General Purpose Alarm' sensor in ExpertUI/Control/Sensors - Always Idle.
In controller.js there is the next 'level' retrieval for '0x9c' class
 `obj['level'] = (val.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));`
should be
 `obj['level'] = (val.sensorState.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));`

Also the parent field of __data.0__ "updateTime" not updated on Alarm report receiving although the child __data.0.sensorState__ is updated with right time. But this, I suppose, the z-way-server issue.

![z wave expert ui - alarm sensor not updated5](https://cloud.githubusercontent.com/assets/5053583/6378962/c67ff4aa-bd3f-11e4-93ee-a40ca2c22e9e.png)

**Comment by PoltoS** [comment]
> Also the parent field of data.0 "updateTime" not updated on Alarm report receiving although the child data.0.sensorState is updated with right time. But this, I suppose, the z-way-server issue.

This was fixed today. Will be in rc16.

**Comment by PoltoS** [comment]
@vades Please check this issue and apply the proposed fix if it is correct

**Comment by vades** [comment]
Is fixed with:
obj['level'] = (val.sensorState.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));

**Comment by dolpheen** [comment]
Another issue while updating sensor in real time in Expert UI.

On sensor state change an empty field apper (you need to reload page to get right status).
In `controllers.js/refreshData()`
for v.cmdId == 0x30
`levelExt = (obj.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));`
should be changed to
`level = (obj.level.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));`

for v.cmdId == 0x9c
`levelExt = (obj.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));`
should be changed to
`level = (obj.sensorState.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));`

![z wave expert ui - alarm sensor not updated6](https://cloud.githubusercontent.com/assets/5053583/6387964/f16e221c-bda4-11e4-8fe4-8345ec47caa3.png)
