### ISSUE TITLE
Sensor data for 'General purpose' sensors not updated in real-time

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/ExpertUI#83]
Another issue while updating sensor in real time in Expert UI.

On sensor state change an empty field apper (you need to reload page to get right status).
In `controllers.js/refreshData()`
for v.cmdId == 0x30
`levelExt = (obj.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));`
should be changed to
`level = (obj.level.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));`

for v.cmdId == 0x9c
`levelExt = (obj.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));`
should be changed to
`level = (obj.sensorState.value ? $scope._t('sensor_triggered') : $scope._t('sensor_idle'));`

![z wave expert ui - alarm sensor not updated6](https://cloud.githubusercontent.com/assets/5053583/6387964/f16e221c-bda4-11e4-8fe4-8345ec47caa3.png)

**Comment by vades** [comment]
Done
