### ISSUE TITLE
MultiAssociation (0x8E) selected instead basic Association (0x85)

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/ExpertUI#84]
2.0.1-rc15 (ex. with Fibaro FGK door sensor)

Device support normal Association(0x85) class. Adding device to group is OK.
There is an error while deleting device, Multichannel Association(0x8E) is selected instead.
Something is messed up with '' and null values for `assocToNode` `assocToInstance` in configuration.js. 
Did not get the right idea in code, but the next workaround resolves the problem in configuration.js/openRemove().
`$scope.assocToNode = null;
$scope.assocToInstance = null;`

![associationcommanderror](https://cloud.githubusercontent.com/assets/5053583/6394826/37a0d6ea-bde5-11e4-822d-7869117132cf.jpg)

**Comment by vades** [comment]
Changed to:
$scope.assocToNode = null; 
$scope.assocToInstance = null;

Please test it

**Comment by dolpheen** [comment]
It works if you don't leave the association tab if you navigate to other menus and come back to association and try to remove device then there is the same 'Error handling' with 0x8e selected.

**Comment by dolpheen** [comment]
On DEV branch it's OK!

**Comment by vades** [comment]
Association code refactored.
