### ISSUE TITLE
Move the "remove" button on the device widget, and show a confirmation window

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#85]
Hi, I checked the work of the Association.
My comments:
1) Device can be added into itself (bad)
2) Move the "remove" button on the device widget, and show a confirmation window
![assoc](https://cloud.githubusercontent.com/assets/2894860/6395010/99d8a0b2-bde6-11e4-8da1-273912a1f622.png)

**Comment by vades** [comment]
Association code refactored.
