### ISSUE TITLE
HTML IDs are same for multiinstance sensors of same type

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/ExpertUI#86]
2.0.1-rc15 (ex. with Fibaro Door sensor with temperature sensor connected)

First mentioned in [#76](https://github.com/Z-Wave-Me/ExpertUI/issues/76)

If device has instances with the same type of sensors (ex. 2 instanses with binary switch), they are assigned same IDs duiring iterating in sensorsController(). So, they are wrongly updated in Control/Sensors interface.

The problem is that in controllers.js/setData() they are assigned with IDs not taking in account the current instance, like that 
`sensorBinary.name + '_' + k +  '_' + sensor_type;`
should be
`sensorBinary.name + '_' + k + '_' + instanceId + '_' + sensor_type;` (at 4 locations in code)

![z wave expert ui same ids for binary sensors](https://cloud.githubusercontent.com/assets/5053583/6399603/8d4bb4c4-be04-11e4-9d3f-af0d13ed4dfb.png)

*Don't know whether the problem can be regarded for other types (not only sensors, thermostats, etc. when instances have the same type)

**Comment by vades** [comment]
Fixed. Now row ID is: alarmSensor.name + '_' + k + '_' + instanceId + '_' + sensor_type
