### ISSUE TITLE
ZDDX rangemapped type not correctly displayed for value = 0

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/ExpertUI#87]
2.0.1-rc16 (ex. with Fibaro FGS-211 switch)
If a rangemapped parameter has value of 0 in it's list, it will never be selected on update or refresh (still we can write it to device but it dissapears in configuration screen in a second after refresh).
In directives.js/expertCommandInput/getEnum code the value is handled like this 
` if (value) `
so, if value is 0 mean False and checking skipped.
Better to hanlde like this
`!isNaN(parseInt(value, 10))`
Totally 2 locations should be fixed in getEnum() code.

![z wave expert ui_rangemapped problem](https://cloud.githubusercontent.com/assets/5053583/6419336/3bc5609a-becd-11e4-840e-ba1e21138d02.png)

**Comment by vades** [comment]
Done
