### ISSUE TITLE
Add descriptions for color value on tab "Timing info"

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#89]
For EN:
Decoding the color values of the response time of the device:  
green - the response time is not beyond the allowable range.
black  - controller was not able to reach the given node with 3 attempts and tried a different route that finally worked.
red     - the communication finally failed after some re-routing attempts.
![timing_en](https://cloud.githubusercontent.com/assets/2894860/6449589/fac20a36-c132-11e4-82e5-4e4d5a26654b.png)

For RU:
Расшифровка цветовых значений времени отклика устройств:  
зеленый - время отклика не выходит за рамки допустимого интервала.
черный   - контроллер не смог связаться с устройством за 3 попытки и использовал другой маршрут, который  привел к успешной передачи сигнала.
красный - контроллер не смог связаться с устройство даже используя другие маршруты.
![timing_ru](https://cloud.githubusercontent.com/assets/2894860/6449640/4ac41cd6-c133-11e4-8073-b30302003e38.png)

**Comment by PoltoS** [comment]
Black: or FLiRS device

**Comment by vades** [comment]
Done
