### ISSUE TITLE
On tab "Timing info" if Last packets < 10ms, show 1, now showing 0

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#90]
On tab "Timinig info" if the response time less than 10 ms
![timing](https://cloud.githubusercontent.com/assets/2894860/6449726/cfb5697c-c133-11e4-9bc3-ba713bed331e.png)
, it shows 0, need to display 1

**Comment by PoltoS** [comment]
0 here means < 10me, but user will mot understand it, so let's write 1 like for 10-19ms

**Comment by vades** [comment]
Done
