### ISSUE TITLE
Association - issues

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/ExpertUI#92]
Association tested on 2.0.1-rc16 (on devices Fibaro Multisensor, Door sensor, WallPlug, Relay x 1, Relay x 2, Z-wave.me KFOB).

In addition to #84, #85 and #78, here is a list of found issues after testing

1. Adding/Removing on instances + 1
ex. we have physically 0,1,2 instanses, in pull-down menu 1,2,3 (and also in z-wave commands), so assigned wrongly.

2. If device have MultiChannelAssociation but have only one instance, MultiChannelAssociation doesn't work (For all Fibaro devices). it works only with normal Association.
Should we handle the devices with only instance[0] with normal Association cmdClass? (even if it has MCA in NIF).

3. If device has several channels [0,1,2], association to channel 0 doesn't work (for all Fibaro devices). Should we hide channel 0 for multichannel device?

4. In pull-down selection for Nodes, all nodes are shown even those that are already included.  ('addDevices' array used, insted of 'addNodesSort' in ng-repeat)

5. If device's instance is selected automatically you need to deselect/select it, or you will get the wrong instance number (just empty string) and error on runCmd.

**Comment by aivs** [comment]
At this moment (v2.0.1-rc35) all the issues are still actual.

**Comment by vades** [comment]
I'm working on new version of the assocciations.

**Comment by vades** [comment]
Association code refactored.
