### ISSUE TITLE
Sensor level for gen.purpose/alarm sensors not updated in real-time

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/ExpertUI#94]
Issue #83 still exists on 2.0.1-rc23
Sensors level updated only after page reload.

![z wave expert ui - sensor level not updated](https://cloud.githubusercontent.com/assets/5053583/6833251/95a4b2d6-d33c-11e4-9665-f346fc357c80.png)

**Comment by PoltoS** [comment]
Martin, please take care of this in next ExpertUI shot

**Comment by dolpheen** [comment]
2.0.1-rc25 Tested with Fibaro door and motion sensor.
Comes to Idle but don't to Trigger(you should refresh the page)

**Comment by vades** [comment]
Did you test it from DEV or MASTER branch? On my site it works.

**Comment by dolpheen** [comment]
Tested on downloaded rc25.
Also tested on DEV and MASTER branches same result

**Comment by vades** [comment]
Fixed
