### ISSUE TITLE
It is a very bad idea to have a Red check mark in front of a failed device

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#97]
I missed a failed device for several days because in the new Expert UI it had a **red** check mark in front of it. A prototypical example of unsafe design principles!
![dead](https://cloud.githubusercontent.com/assets/7747627/7083076/a193d91e-df5d-11e4-8f4c-a5ed6845fa46.PNG)

I do prefer the symbol used in old blue interface which lets little room for ambiguity

PS: I do have red/green vision difficulty :)

**Comment by vades** [comment]
Failed device icon replaced

**Comment by pz1** [comment]
Thanks :)
